import { Question } from '../types';

export const cglQuestions: Question[] = [
  // --- Maths (Harder) ---
  // Number System (10)
  { id: 1001, question: "What is the remainder when 17^200 is divided by 18?", options: ["1", "2", "16", "17"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'number-system', translation: { question: "17^200 को 18 से विभाजित करने पर शेषफल क्या है?", options: ["1", "2", "16", "17"] } },
  { id: 1002, question: "The sum of the digits of a two-digit number is 9. If 27 is added to the number, the digits get reversed. Find the number.", options: ["27", "36", "45", "63"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'number-system', translation: { question: "दो अंकों की संख्या के अंकों का योग 9 है। यदि संख्या में 27 जोड़ा जाता है, तो अंक उलट जाते हैं। संख्या ज्ञात कीजिए।", options: ["27", "36", "45", "63"] } },
  { id: 1003, question: "Find the number of trailing zeros in 100!.", options: ["24", "25", "20", "21"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'number-system', translation: { question: "100! में अनुगामी शून्य की संख्या ज्ञात कीजिए।", options: ["24", "25", "20", "21"] } },
  { id: 1004, question: "A number when divided by 296 gives a remainder of 75. What will be the remainder when the same number is divided by 37?", options: ["1", "2", "8", "11"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'number-system', translation: { question: "एक संख्या को 296 से विभाजित करने पर 75 शेष बचता है। उसी संख्या को 37 से विभाजित करने पर शेषफल क्या होगा?", options: ["1", "2", "8", "11"] } },
  { id: 1005, question: "The unit digit of (347)^153 * (251)^72 is:", options: ["1", "3", "7", "9"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'number-system', translation: { question: "(347)^153 * (251)^72 का इकाई अंक है:", options: ["1", "3", "7", "9"] } },
  { id: 1006, question: "The HCF and LCM of two numbers are 12 and 924 respectively. If one number is 84, find the other number.", options: ["132", "124", "112", "144"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'number-system', translation: { question: "दो संख्याओं का HCF और LCM क्रमशः 12 और 924 है। यदि एक संख्या 84 है, तो दूसरी संख्या ज्ञात कीजिए।", options: ["132", "124", "112", "144"] } },
  { id: 1007, question: "What is the smallest number that must be added to 1056 so that the sum is completely divisible by 23?", options: ["2", "3", "18", "21"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'number-system', translation: { question: "1056 में कौन सी सबसे छोटी संख्या जोड़ी जानी चाहिए ताकि योग 23 से पूरी तरह से विभाज्य हो?", options: ["2", "3", "18", "21"] } },
  { id: 1008, question: "Find the value of 1 - 2 + 3 - 4 + 5 - ... + 99 - 100.", options: ["-50", "50", "-55", "55"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'number-system', translation: { question: "1 - 2 + 3 - 4 + 5 - ... + 99 - 100 का मान ज्ञात कीजिए।", options: ["-50", "50", "-55", "55"] } },
  { id: 1009, question: "If the number 481*673 is completely divisible by 9, then the smallest whole number in place of * will be:", options: ["2", "5", "6", "7"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CGL', chapter: 'number-system', translation: { question: "यदि संख्या 481*673, 9 से पूरी तरह विभाज्य है, तो * के स्थान पर सबसे छोटी पूर्ण संख्या क्या होगी:", options: ["2", "5", "6", "7"] } },
  { id: 1010, question: "The sum of all prime numbers between 58 and 68 is:", options: ["179", "178", "187", "183"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'number-system', translation: { question: "58 और 68 के बीच की सभी अभाज्य संख्याओं का योग है:", options: ["179", "178", "187", "183"] } },

  // Percentages (10)
  { id: 1011, question: "A's salary is 40% of B's salary and B's salary is 25% of C's salary. What percentage of C's salary is A's salary?", options: ["5%", "10%", "15%", "20%"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'percentages' },
  { id: 1012, question: "In an examination, 65% of the students passed in Mathematics, 48% passed in Physics and 30% passed in both. How much percent of students failed in both the subjects?", options: ["17%", "15%", "13%", "12%"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'percentages' },
  { id: 1013, question: "The price of sugar is increased by 20%. By what percent must a housewife reduce the consumption of sugar so that the expenditure on sugar remains the same?", options: ["15%", "16.66%", "20%", "25%"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'percentages' },
  { id: 1014, question: "In an election between two candidates, one got 55% of the total valid votes, 20% of the votes were invalid. If the total number of votes was 7500, the number of valid votes that the other candidate got was:", options: ["2700", "2900", "3000", "3100"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'percentages' },
  { id: 1015, question: "A number is increased by 20% and then decreased by 20%. The final value of the number is:", options: ["decreased by 4%", "increased by 4%", "does not change", "decreased by 2%"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'percentages' },
  { id: 1016, question: "If the radius of a circle is increased by 50%, its area is increased by:", options: ["125%", "100%", "75%", "50%"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'percentages' },
  { id: 1017, question: "Out of her total income, Neelam spends 20% on house rent and 70% of the rest on household expenditure. If she saves Rs. 3600, what is her total income?", options: ["Rs. 15000", "Rs. 18000", "Rs. 12000", "Rs. 20000"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'percentages' },
  { id: 1018, question: "A student has to obtain 33% of the total marks to pass. He got 125 marks and failed by 40 marks. The maximum marks are:", options: ["300", "500", "800", "1000"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'percentages' },
  { id: 1019, question: "The population of a town was 1,60,000 three years ago. If it increased by 3%, 2.5% and 5% respectively in the last three years, then the present population is:", options: ["177366", "177461", "177561", "177661"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'percentages' },
  { id: 1020, question: "Two numbers are respectively 20% and 50% more than a third number. The ratio of the two numbers is:", options: ["2:5", "3:5", "4:5", "6:7"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'percentages' },
  
  // Ratio and Proportion (10)
  { id: 1021, question: "If A:B = 5:7 and B:C = 6:11, then A:B:C is:", options: ["55:77:66", "30:42:77", "35:49:42", "None of these"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'ratio-proportion' },
  { id: 1022, question: "The fourth proportional to 4, 9, 12 is:", options: ["18", "27", "36", "16"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'ratio-proportion' },
  { id: 1023, question: "A bag contains 50 P, 25 P and 10 P coins in the ratio 5: 9: 4, amounting to Rs. 206. Find the number of coins of each type.", options: ["200, 360, 160", "250, 300, 150", "200, 300, 200", "250, 360, 160"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'ratio-proportion' },
  { id: 1024, question: "If Rs. 782 be divided into three parts, proportional to 1/2 : 2/3 : 3/4, then the first part is:", options: ["Rs. 182", "Rs. 190", "Rs. 196", "Rs. 204"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CGL', chapter: 'ratio-proportion' },
  { id: 1025, question: "The ratio of two numbers is 3:4 and their HCF is 4. Their LCM is:", options: ["12", "16", "24", "48"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CGL', chapter: 'ratio-proportion' },
  { id: 1026, question: "The salaries of A, B, and C are in the ratio 2:3:5. If the increments of 15%, 10% and 20% are allowed respectively in their salaries, then what will be the new ratio of their salaries?", options: ["3:3:10", "10:11:20", "23:33:60", "Cannot be determined"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'ratio-proportion' },
  { id: 1027, question: "What must be added to each term of the ratio 7 : 13 so that the ratio becomes 2 : 3?", options: ["1", "2", "3", "5"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CGL', chapter: 'ratio-proportion' },
  { id: 1028, question: "A mixture contains alcohol and water in the ratio 4:3. If 5 liters of water is added to the mixture, the ratio becomes 4:5. The quantity of alcohol in the given mixture is:", options: ["10 liters", "8 liters", "12 liters", "15 liters"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'ratio-proportion' },
  { id: 1029, question: "The third proportional to 9 and 12 is:", options: ["10.5", "16", "14", "18"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'ratio-proportion' },
  { id: 1030, question: "The sum of three numbers is 98. If the ratio of the first to the second is 2:3 and that of the second to the third is 5:8, then the second number is:", options: ["20", "30", "48", "58"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'ratio-proportion' },

  // Averages (10)
  { id: 1031, question: "The average of first 50 natural numbers is:", options: ["25.30", "25.5", "25.00", "12.25"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'averages' },
  { id: 1032, question: "The average of first 5 prime numbers is:", options: ["5", "5.6", "5.4", "6"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'averages' },
  { id: 1033, question: "The average age of a class of 39 students is 15 years. If the age of the teacher is included, then the average increases by 3 months. Find the age of the teacher.", options: ["25 years", "27 years", "30 years", "32 years"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'averages' },
  { id: 1034, question: "The average of 5 consecutive numbers is n. If the next two numbers are also included, the average will:", options: ["remain the same", "increase by 1", "increase by 1.4", "increase by 2"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'averages' },
  { id: 1035, question: "A batsman makes a score of 87 runs in the 17th inning and thus increases his average by 3. Find his average after 17th inning.", options: ["39", "36", "42", "45"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'averages' },
  { id: 1036, question: "The average weight of 16 boys in a class is 50.25 kg and that of the remaining 8 boys is 45.15 kg. Find the average weight of all the boys in the class.", options: ["47.55 kg", "48 kg", "48.55 kg", "49.25 kg"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'averages' },
  { id: 1037, question: "The average of 11 results is 60. If the average of first six results is 58 and that of the last six is 63, find the sixth result.", options: ["66", "60", "57", "65"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'averages' },
  { id: 1038, question: "The average monthly income of P and Q is Rs. 5050. The average monthly income of Q and R is Rs. 6250 and the average monthly income of P and R is Rs. 5200. The monthly income of P is:", options: ["3500", "4000", "4050", "5000"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'averages' },
  { id: 1039, question: "The average age of husband, wife and their child 3 years ago was 27 years and that of wife and the child 5 years ago was 20 years. The present age of the husband is:", options: ["35 years", "40 years", "50 years", "None of these"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'averages' },
  { id: 1040, question: "The average of 20 numbers is zero. Of them, at the most, how many may be greater than zero?", options: ["0", "1", "10", "19"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CGL', chapter: 'averages' },

  // Simple and Compound Interest (10)
  { id: 1041, question: "A sum of money at simple interest amounts to Rs. 815 in 3 years and to Rs. 854 in 4 years. The sum is:", options: ["Rs. 650", "Rs. 690", "Rs. 698", "Rs. 700"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'si-ci' },
  { id: 1042, question: "The compound interest on Rs. 30,000 at 7% per annum for a certain time is Rs. 4347. The time is:", options: ["2 years", "2.5 years", "3 years", "4 years"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'si-ci' },
  { id: 1043, question: "What is the difference between the compound interests on Rs. 5000 for 1.5 years at 4% per annum compounded yearly and half-yearly?", options: ["Rs. 2.04", "Rs. 3.06", "Rs. 4.80", "Rs. 8.30"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'si-ci' },
  { id: 1044, question: "At what rate percent per annum will a sum of money double in 16 years?", options: ["5%", "6%", "6.25%", "6.5%"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'si-ci' },
  { id: 1045, question: "A sum of Rs. 12,500 amounts to Rs. 15,500 in 4 years at the rate of simple interest. What is the rate of interest?", options: ["3%", "4%", "5%", "6%"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CGL', chapter: 'si-ci' },
  { id: 1046, question: "The difference between simple and compound interests compounded annually on a certain sum of money for 2 years at 4% per annum is Re. 1. The sum (in Rs.) is:", options: ["625", "630", "640", "650"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'si-ci' },
  { id: 1047, question: "If the simple interest on a sum of money for 2 years at 5% per annum is Rs. 50, what is the compound interest on the same sum at the same rate and for the same time?", options: ["Rs. 51.25", "Rs. 52", "Rs. 54", "Rs. 55"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'si-ci' },
  { id: 1048, question: "A sum of money becomes 8 times of itself in 3 years at compound interest. The rate of interest per annum is:", options: ["100%", "80%", "20%", "10%"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'si-ci' },
  { id: 1049, question: "In what time will Rs. 8000 at 3% per annum produce the same interest as Rs. 6000 does in 5 years at 4% simple interest?", options: ["3 years", "4 years", "5 years", "6 years"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'si-ci' },
  { id: 1050, question: "A sum of money lent out at simple interest amounts to Rs. 720 after 2 years and to Rs. 1020 after a further period of 5 years. The sum is:", options: ["Rs. 500", "Rs. 600", "Rs. 700", "Rs. 710"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'si-ci' },

  // Profit, Loss and Discount (10)
  { id: 1051, question: "A man buys an article for Rs. 27.50 and sells it for Rs. 28.60. Find his gain percent.", options: ["3%", "4%", "5%", "6%"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'profit-loss-discount' },
  { id: 1052, question: "If the cost price is 95% of the selling price, what is the profit percent?", options: ["4%", "4.75%", "5%", "5.26%"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CGL', chapter: 'profit-loss-discount' },
  { id: 1053, question: "A shopkeeper professes to sell his goods at cost price but uses a weight of 960 gm for a kg weight. Find his gain percent.", options: ["4%", "4 1/6 %", "3 1/3 %", "4 1/2 %"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'profit-loss-discount' },
  { id: 1054, question: "A dealer marked his goods at 20% above the cost price and allowed a discount of 10%. His profit percent is:", options: ["10%", "8%", "9%", "12%"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'profit-loss-discount' },
  { id: 1055, question: "The marked price of a watch was Rs. 720. A man bought the same for Rs. 550.80 after getting two successive discounts, the first being 10%. What was the second discount rate?", options: ["12%", "14%", "15%", "18%"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'profit-loss-discount' },
  { id: 1056, question: "By selling an article for Rs. 100, a man gains Rs. 15. Then his gain % is:", options: ["15%", "12 1/2 %", "17 11/17 %", "17 1/4 %"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'profit-loss-discount' },
  { id: 1057, question: "The cost price of 20 articles is the same as the selling price of x articles. If the profit is 25%, then the value of x is:", options: ["15", "16", "18", "25"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'profit-loss-discount' },
  { id: 1058, question: "A dishonest dealer uses a scale of 90 cm instead of a meter scale and claims to sell at cost price. His profit is:", options: ["9%", "10%", "11 1/9 %", "12%"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'profit-loss-discount' },
  { id: 1059, question: "A man sold two flats for Rs. 6,75,958 each. On one he gains 16% while on the other he loses 16%. His gain or loss percent in the whole transaction is:", options: ["2.56% loss", "2.56% gain", "No profit, no loss", "16% loss"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'profit-loss-discount' },
  { id: 1060, question: "If the selling price is doubled, the profit triples. Find the profit percent.", options: ["66 2/3", "100", "105 1/3", "120"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'profit-loss-discount' },

  // Mixtures and Allegations (10)
  { id: 1061, question: "In what ratio must a grocer mix two varieties of pulses costing Rs. 15 and Rs. 20 per kg respectively so as to get a mixture worth Rs. 16.50 per kg?", options: ["3 : 7", "5 : 7", "7 : 3", "7 : 5"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'mixtures-allegations' },
  { id: 1062, question: "A dishonest milkman professes to sell his milk at cost price but he mixes it with water and thereby gains 25%. The percentage of water in the mixture is:", options: ["4%", "6 1/4%", "20%", "25%"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'mixtures-allegations' },
  { id: 1063, question: "A can contains a mixture of two liquids A and B in the ratio 7 : 5. When 9 litres of mixture are drawn off and the can is filled with B, the ratio of A and B becomes 7 : 9. How many litres of liquid A was contained by the can initially?", options: ["10", "20", "21", "25"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'mixtures-allegations' },
  { id: 1064, question: "In what ratio must water be mixed with milk to gain 16 2/3% on selling the mixture at cost price?", options: ["1 : 6", "6 : 1", "2 : 3", "4 : 3"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'mixtures-allegations' },
  { id: 1065, question: "Two vessels A and B contain spirit and water mixed in the ratio 5:2 and 7:6 respectively. Find the ratio in which these mixtures be mixed to obtain a new mixture in vessel C containing spirit and water in the ratio 8:5.", options: ["4 : 3", "3 : 4", "5 : 6", "7 : 9"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CGL', chapter: 'mixtures-allegations' },
  { id: 1066, question: "A milk vendor has 2 cans of milk. The first contains 25% water and the rest milk. The second contains 50% water. How much milk should he mix from each of the containers so as to get 12 litres of milk such that the ratio of water to milk is 3 : 5?", options: ["4 litres, 8 litres", "6 litres, 6 litres", "5 litres, 7 litres", "7 litres, 5 litres"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'mixtures-allegations' },
  { id: 1067, question: "A mixture of 30 litres of milk and water contains 10% of water. How much water must be added to it so that water may be 25% of the mixture?", options: ["4 litres", "5 litres", "6 litres", "8 litres"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'mixtures-allegations' },
  { id: 1068, question: "A vessel is filled with liquid, 3 parts of which are water and 5 parts syrup. How much of the mixture must be drawn off and replaced with water so that the mixture may be half water and half syrup?", options: ["1/3", "1/4", "1/5", "1/7"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'mixtures-allegations' },
  { id: 1069, question: "Tea worth Rs. 126 per kg and Rs. 135 per kg are mixed with a third variety in the ratio 1 : 1 : 2. If the mixture is worth Rs. 153 per kg, the price of the third variety per kg will be:", options: ["Rs. 169.50", "Rs. 170", "Rs. 175.50", "Rs. 180"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'mixtures-allegations' },
  { id: 1070, question: "How many kilograms of sugar costing Rs. 9 per kg must be mixed with 27 kg of sugar costing Rs. 7 per kg so that there may be a gain of 10% by selling the mixture at Rs. 9.24 per kg?", options: ["36 kg", "42 kg", "54 kg", "63 kg"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CGL', chapter: 'mixtures-allegations' },

  // Time and Work (10)
  { id: 1071, question: "A can do a work in 15 days and B in 20 days. If they work on it together for 4 days, then the fraction of the work that is left is :", options: ["1/4", "1/10", "7/15", "8/15"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CGL', chapter: 'time-work' },
  { id: 1072, question: "A and B can do a piece of work in 72 days; B and C can do it in 120 days; A and C can do it in 90 days. In how many days can A alone do the work?", options: ["80 days", "100 days", "120 days", "150 days"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'time-work' },
  { id: 1073, question: "A is twice as good a workman as B and together they finish a piece of work in 18 days. In how many days will A alone finish the work?", options: ["24", "27", "30", "36"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'time-work' },
  { id: 1074, question: "A and B can do a job together in 7 days. A is 1 3/4 times as efficient as B. The same job can be done by A alone in:", options: ["9 1/3 days", "11 days", "12 1/4 days", "16 1/3 days"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'time-work' },
  { id: 1075, question: "A and B can complete a work in 15 days and 10 days respectively. They started doing the work together but after 2 days B had to leave and A alone completed the remaining work. The whole work was completed in:", options: ["8 days", "10 days", "12 days", "15 days"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'time-work' },
  { id: 1076, question: "4 men and 6 women can complete a work in 8 days, while 3 men and 7 women can complete it in 10 days. In how many days will 10 women complete it?", options: ["35", "40", "45", "50"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'time-work' },
  { id: 1077, question: "A can finish a work in 18 days and B can do the same work in 15 days. B worked for 10 days and left the job. In how many days, A alone can finish the remaining work?", options: ["5", "5 1/2", "6", "8"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'time-work' },
  { id: 1078, question: "Two pipes A and B can fill a tank in 20 and 30 minutes respectively. If both the pipes are used together, then how long will it take to fill the tank?", options: ["12 min", "15 min", "25 min", "50 min"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'time-work' },
  { id: 1079, question: "A tap can fill a tank in 6 hours. After half the tank is filled, three more similar taps are opened. What is the total time taken to fill the tank completely?", options: ["3 hrs 15 min", "3 hrs 45 min", "4 hrs", "4 hrs 15 min"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'time-work' },
  { id: 1080, question: "10 women can complete a work in 7 days and 10 children take 14 days to complete the work. How many days will 5 women and 10 children take to complete the work?", options: ["3", "5", "7", "Cannot be determined"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'time-work' },

  // Time, Speed and Distance (10)
  { id: 1081, question: "A person crosses a 600 m long street in 5 minutes. What is his speed in km per hour?", options: ["3.6", "7.2", "8.4", "10"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'time-speed-distance' },
  { id: 1082, question: "A train running at the speed of 60 km/hr crosses a pole in 9 seconds. What is the length of the train?", options: ["120 metres", "180 metres", "324 metres", "150 metres"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CGL', chapter: 'time-speed-distance' },
  { id: 1083, question: "A man on tour travels first 160 km at 64 km/hr and the next 160 km at 80 km/hr. The average speed for the first 320 km of the tour is:", options: ["35.55 km/hr", "36 km/hr", "71.11 km/hr", "71 km/hr"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'time-speed-distance' },
  { id: 1084, question: "Excluding stoppages, the speed of a bus is 54 kmph and including stoppages, it is 45 kmph. For how many minutes does the bus stop per hour?", options: ["9", "10", "12", "20"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'time-speed-distance' },
  { id: 1085, question: "Two trains of equal length are running on parallel lines in the same direction at 46 km/hr and 36 km/hr. The faster train passes the slower train in 36 seconds. The length of each train is:", options: ["50 m", "72 m", "80 m", "82 m"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'time-speed-distance' },
  { id: 1086, question: "A man walking at the rate of 5 km/hr crosses a bridge in 15 minutes. The length of the bridge (in metres) is:", options: ["600", "750", "1000", "1250"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CGL', chapter: 'time-speed-distance' },
  { id: 1087, question: "How long does a train 110 metres long running at the speed of 72 km/hr take to cross a bridge 132 metres in length?", options: ["9.8 sec", "12.1 sec", "12.42 sec", "14.3 sec"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'time-speed-distance' },
  { id: 1088, question: "A man can row upstream at 8 kmph and downstream at 13 kmph. The speed of the stream is:", options: ["2.5 kmph", "4.2 kmph", "5 kmph", "10.5 kmph"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'time-speed-distance' },
  { id: 1089, question: "A car travelling with 5/7 of its usual speed covers 42 km in 1 hour 40 min 48 sec. What is the usual speed of the car?", options: ["17.5 km/hr", "25 km/hr", "30 km/hr", "35 km/hr"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CGL', chapter: 'time-speed-distance' },
  { id: 1090, question: "If a person walks at 14 km/hr instead of 10 km/hr, he would have walked 20 km more. The actual distance travelled by him is:", options: ["50 km", "56 km", "70 km", "80 km"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'time-speed-distance' },

  // Partnership (10)
  { id: 1091, question: "A, B and C started a business with their investments in the ratio 1 : 3 : 5. After 4 months, A invested the same amount as before and B as well as C withdrew half of their investments. The ratio of their profits at the end of the year is:", options: ["4 : 3 : 5", "5 : 6 : 10", "6 : 5 : 10", "10 : 5 : 6"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'partnership' },
  { id: 1092, question: "A and B start a business with investments of Rs. 3,50,000 and Rs. 1,40,000, respectively. A gets 20% of the yearly profit for managing the business. Thereafter the profit is divided in the ratio of the capital. If A receives a total of Rs. 38,000 more than B, the total profit is:", options: ["Rs. 2,80,000", "Rs. 70,000", "Rs. 2,10,000", "Rs. 1,05,000"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'partnership' },
  { id: 1093, question: "A, B, C subscribe Rs. 50,000 for a business. A subscribes Rs. 4000 more than B and B Rs. 5000 more than C. Out of a total profit of Rs. 35,000, A receives:", options: ["Rs. 8400", "Rs. 11,900", "Rs. 13,600", "Rs. 14,700"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CGL', chapter: 'partnership' },
  { id: 1094, question: "A and B entered into partnership with capitals in the ratio 4 : 5. After 3 months, A withdrew 1/4 of his capital and B withdrew 1/5 of his capital. The gain at the end of 10 months was Rs. 760. A's share in this profit is:", options: ["Rs. 330", "Rs. 360", "Rs. 380", "Rs. 430"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'partnership' },
  { id: 1095, question: "A, B and C start a business each investing Rs. 20,000. After 5 months A withdrew Rs. 5000, B withdrew Rs. 4000 and C invests Rs. 6000 more. At the end of the year, a total profit of Rs. 69,900 was recorded. Find the share of B.", options: ["Rs. 20,500", "Rs. 21,200", "Rs. 28,200", "Rs. 27,300"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'partnership' },
  { id: 1096, question: "A and B invest in a business in the ratio 3 : 2. If 5% of the total profit goes to charity and A's share is Rs. 855, the total profit is:", options: ["Rs. 1425", "Rs. 1500", "Rs. 1537.50", "Rs. 1576"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'partnership' },
  { id: 1097, question: "A began a business with Rs. 85,000. He was joined afterwards by B with Rs. 42,500. For how much period does B join, if the profits at the end of the year are divided in the ratio of 3 : 1?", options: ["4 months", "5 months", "6 months", "8 months"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CGL', chapter: 'partnership' },
  { id: 1098, question: "A and B are partners in a business. A contributes 1/4 of the capital for 15 months and B received 2/3 of the profit. For how long B's money was used?", options: ["6 months", "8 months", "10 months", "12 months"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'partnership' },
  { id: 1099, question: "Anand and Deepak started a business investing Rs. 22,500 and Rs. 35,000 respectively. Out of a total profit of Rs. 13,800, Deepak's share is:", options: ["Rs. 5400", "Rs. 7200", "Rs. 8400", "Rs. 9600"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'partnership' },
  { id: 1100, question: "A, B, C enter into a partnership. A invests some money at the beginning, B invests double the amount after 6 months and C invests thrice the amount after 8 months. If the annual profit be Rs. 27,000, C's share is:", options: ["Rs. 8625", "Rs. 9000", "Rs. 10,800", "Rs. 11,250"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'partnership' },


  // Algebra (10)
  { id: 1101, question: "If x = (√3 + 1) / (√3 - 1) and y = (√3 - 1) / (√3 + 1), then the value of x² + y² is:", options: ["14", "13", "15", "10"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'algebra'},
  { id: 1102, question: "If x + 1/x = 5, then the value of x⁶ + 1/x⁶ is:", options: ["12098", "12048", "14088", "14048"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'algebra'},
  { id: 1103, question: "If a + b + c = 0, then the value of (a³ + b³ + c³) is:", options: ["0", "1", "3abc", "abc"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'algebra'},
  { id: 1104, question: "If x² + 1/x² = 98, then the value of x³ + 1/x³ is:", options: ["970", "1030", "790", "-970"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'algebra'},
  { id: 1105, question: "If 2x - 1/2x = 6, then the value of 4x² + 1/4x² is:", options: ["38", "34", "30", "40"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'algebra'},
  { id: 1106, question: "The factors of (x⁴ + x²y² + y⁴) are:", options: ["(x²+y²+xy)(x²+y²-xy)", "(x²-y²-xy)(x²+y²+xy)", "(x²+y²)(x²-y²)", "(x+y)(x-y)(x²+y²)"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'algebra'},
  { id: 1107, question: "If x = 7 - 4√3, the value of (x¹/² + x⁻¹/²) is:", options: ["1", "2", "3√3", "4"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CGL', chapter: 'algebra'},
  { id: 1108, question: "If (x/y)^(a-4) = (y/x)^(2a-5), what is the value of a?", options: ["3", "1", "2", "9"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'algebra'},
  { id: 1109, question: "For what value of k, the expression x⁶ - 18x³ + k is a perfect square?", options: ["-81", "81", "-27", "27"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'algebra'},
  { id: 1110, question: "If x = ∛5 + 2, then the value of x³ - 6x² + 12x - 13 is:", options: ["-1", "0", "1", "2"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'algebra'},

  // Geometry (10)
  { id: 1201, question: "The lengths of the three medians of a triangle are 9 cm, 12 cm and 15 cm. The area (in sq. cm) of the triangle is", options: ["24", "72", "48", "144"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'geometry'},
  { id: 1202, question: "If the incentre of an equilateral triangle lies inside the triangle and its radius is 3 cm, then the side of the equilateral triangle is", options: ["9√3 cm", "6√3 cm", "3√3 cm", "6 cm"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'geometry'},
  { id: 1203, question: "In a circle with center O, AB is a diameter and CD is a chord such that ABCD is a trapezium. If ∠BAC = 15°, then ∠CAD is equal to:", options: ["45°", "60°", "75°", "30°"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'geometry'},
  { id: 1204, question: "Two circles touch each other externally. The distance between their centers is 7 cm. If the radius of one circle is 4 cm, then the radius of the other circle is:", options: ["3.5 cm", "3 cm", "4 cm", "2.5 cm"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'geometry'},
  { id: 1205, question: "The length of the tangent from an external point P to a circle of radius 5 cm is 12 cm. The distance of P from the center is:", options: ["13 cm", "11 cm", "17 cm", "7 cm"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'geometry'},
  { id: 1206, question: "ABCD is a cyclic quadrilateral and AB is a diameter. If ∠ADC = 140°, then ∠BAC is equal to:", options: ["30°", "40°", "50°", "60°"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'geometry'},
  { id: 1207, question: "The angle of elevation of the top of a tower from a point on the ground is 30°. On walking 40m towards the tower, the angle of elevation becomes 60°. The height of the tower is:", options: ["20√3 m", "10√3 m", "20 m", "10 m"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'geometry'},
  { id: 1208, question: "If the diagonals of a rhombus are 16 cm and 12 cm, then the length of the side of the rhombus is:", options: ["8 cm", "9 cm", "10 cm", "12 cm"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'geometry'},
  { id: 1209, question: "The area of a triangle is 216 cm² and its sides are in the ratio 3 : 4 : 5. The perimeter of the triangle is:", options: ["6 cm", "12 cm", "36 cm", "72 cm"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CGL', chapter: 'geometry'},
  { id: 1210, question: "The ratio of the length of a side of an equilateral triangle to its height is:", options: ["1:√3", "2:√3", "√3:2", "√3:1"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'geometry'},

  // Trigonometry (10)
  { id: 1301, question: "The value of (sin 30° + cos 30°) – (sin 60° + cos 60°) is", options: ["0", "1", "2", "-1"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'trigonometry'},
  { id: 1302, question: "If tan(θ) + cot(θ) = 2, then the value of tan²⁰(θ) + cot²⁰(θ) is:", options: ["0", "2", "2²⁰", "2¹⁰"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'trigonometry'},
  { id: 1303, question: "If sin(θ) + cosec(θ) = 2, then sin¹⁰⁰(θ) + cosec¹⁰⁰(θ) is equal to:", options: ["1", "2", "100", "200"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'trigonometry'},
  { id: 1304, question: "The value of tan 1° tan 2° tan 3° ... tan 89° is:", options: ["1", "0", "undefined", "1/2"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'trigonometry'},
  { id: 1305, question: "If cos⁴(A) - sin⁴(A) = x, then value of x is:", options: ["cos²(A) - sin²(A)", "cos(2A)", "2cos²(A) - 1", "All of the above"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CGL', chapter: 'trigonometry'},
  { id: 1306, question: "The minimum value of 2sin²(θ) + 3cos²(θ) is:", options: ["0", "1", "2", "3"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'trigonometry'},
  { id: 1307, question: "If sin(A - B) = 1/2 and cos(A + B) = 1/2, where A > B > 0, then the value of A is:", options: ["45°", "60°", "15°", "30°"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'trigonometry'},
  { id: 1308, question: "The value of (sec²θ - 1)(cosec²θ - 1) is:", options: ["1", "0", "sin²θ", "cos²θ"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'trigonometry'},
  { id: 1309, question: "What is the value of (1 + tan²θ) / (1 + cot²θ)?", options: ["sec²θ", "tan²θ", "cos²θ", "-1"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'trigonometry'},
  { id: 1310, question: "If 5tan(θ) = 4, then (5sin(θ) - 3cos(θ)) / (5sin(θ) + 2cos(θ)) is equal to:", options: ["5/14", "1/6", "1/3", "3/5"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'trigonometry'},
  
  // Mensuration (10)
  { id: 1401, question: "The diagonal of a cube is 4√3 cm. Its volume is:", options: ["16 cm³", "27 cm³", "64 cm³", "81 cm³"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'mensuration' },
  { id: 1402, question: "If the radius of a sphere is doubled, its volume becomes:", options: ["2 times", "4 times", "6 times", "8 times"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CGL', chapter: 'mensuration' },
  { id: 1403, question: "The area of the largest triangle that can be inscribed in a semi-circle of radius r is:", options: ["r²", "2r²", "r³/2", "r²/2"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'mensuration' },
  { id: 1404, question: "A wire can be bent in the form of a circle of radius 56 cm. If it is bent in the form of a square, then its area will be:", options: ["3520 cm²", "7744 cm²", "5600 cm²", "8800 cm²"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'mensuration' },
  { id: 1405, question: "The lengths of the diagonals of a rhombus are 24 cm and 10 cm. The perimeter of the rhombus is:", options: ["52 cm", "56 cm", "60 cm", "68 cm"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'mensuration' },
  { id: 1406, question: "The volume of a right circular cone is 1232 cm³ and its vertical height is 24 cm. Its curved surface area is:", options: ["154 cm²", "550 cm²", "604 cm²", "704 cm²"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'mensuration' },
  { id: 1407, question: "The circumference of a circle is 100 cm. The side of a square inscribed in the circle is:", options: ["50√2 cm", "100/√π cm", "50√2/π cm", "100√2/π cm"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'mensuration' },
  { id: 1408, question: "The area of a sector of a circle of radius 5 cm, formed by an arc of length 3.5 cm is:", options: ["8.5 cm²", "8.75 cm²", "7.75 cm²", "7.5 cm²"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'mensuration' },
  { id: 1409, question: "A 20 m deep well with diameter 7 m is dug and the earth from digging is evenly spread out to form a platform 22 m by 14 m. The height of the platform is:", options: ["2 m", "2.5 m", "3 m", "3.5 m"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'mensuration' },
  { id: 1410, question: "The surface areas of two spheres are in the ratio 4 : 9. The ratio of their volumes is:", options: ["2:3", "4:9", "8:27", "16:81"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'mensuration' },
  
  // Statistics, Probability, DI, Coordinate Geometry (10)
  { id: 1501, question: "The mode and mean is given by 7 and 8 respectively. The median is:", options: ["1/13", "13/3", "23/3", "33"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'statistics' },
  { id: 1502, question: "What is the probability of getting a sum 9 from two throws of a dice?", options: ["1/6", "1/8", "1/9", "1/12"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'probability' },
  { id: 1503, question: "Study the pie-chart and answer the question. The total expenditure of a family is Rs 10800. What is the expenditure on food? (Food=120°, Others=60°, Clothing=50°, Education=70°, House Rent=60°)", options: ["Rs 3600", "Rs 3000", "Rs 2100", "Rs 1800"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'di' },
  { id: 1504, question: "The distance of the point (4, -3) from the origin is:", options: ["1", "5", "7", "25"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'coordinate-geometry' },
  { id: 1505, question: "The arithmetic mean of the first 10 whole numbers is:", options: ["4.5", "5", "5.5", "6"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'statistics' },
  { id: 1506, question: "A card is drawn from a pack of 52 cards. The probability of getting a queen of club or a king of heart is:", options: ["1/13", "2/13", "1/26", "1/52"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CGL', chapter: 'probability' },
  { id: 1507, question: "The x-intercept of the graph of the equation 3x + 4y = 12 is:", options: ["3", "4", "12", "7"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CGL', chapter: 'coordinate-geometry' },
  { id: 1508, question: "The percentage of marks obtained by students of a class in mathematics are 64, 36, 48, 84, 93, 72, 29, 68, 51. The range of the data is:", options: ["64", "65", "68", "93"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'statistics' },
  { id: 1509, question: "In a single throw of two dice, find the probability of getting a total of 11.", options: ["1/18", "1/36", "1/9", "1/6"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CGL', chapter: 'probability' },
  { id: 1510, question: "The point which divides the line segment joining the points (7, –6) and (3, 4) in the ratio 1 : 2 internally lies in the:", options: ["I quadrant", "II quadrant", "III quadrant", "IV quadrant"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CGL', chapter: 'coordinate-geometry' },

  // --- General Studies (Harder) - 250 questions ---
  ...Array.from({ length: 250 }, (_, i) => {
    const questions = [
      { id: 2001, question: "Which article of the Indian Constitution deals with the abolition of titles?", options: ["Article 16", "Article 17", "Article 18", "Article 19"], correctAnswerIndex: 2 },
      { id: 2002, question: "The Ryotwari System was introduced by Thomas Munro in which region of India?", options: ["Bengal and Bihar", "Madras and Bombay Presidencies", "United Provinces", "Central Provinces"], correctAnswerIndex: 1 },
      { id: 2003, question: "Which of the following is NOT a primary greenhouse gas found in the Earth's atmosphere?", options: ["Carbon Dioxide", "Methane", "Nitrous Oxide", "Sulphur Dioxide"], correctAnswerIndex: 3 },
      { id: 2004, question: "The concept of 'Judicial Review' in the Indian Constitution has been taken from the Constitution of:", options: ["United Kingdom", "USA", "Canada", "Australia"], correctAnswerIndex: 1 },
      { id: 2005, question: "Who among the following was the founder of the 'Ghadar Party'?", options: ["Lala Har Dayal", "Bhagat Singh", "Subhas Chandra Bose", "Chandrashekhar Azad"], correctAnswerIndex: 0 },
      { id: 2006, question: "The Battle of Plassey was fought in the year:", options: ["1757", "1764", "1857", "1772"], correctAnswerIndex: 0 },
      { id: 2007, question: "Which of the following rivers is also known as 'Dakshin Ganga'?", options: ["Godavari", "Krishna", "Mahanadi", "Cauvery"], correctAnswerIndex: 0 },
      { id: 2008, question: "Myopia is a defect of the human eye. It can be corrected by using a lens called:", options: ["Concave lens", "Convex lens", "Bifocal lens", "Cylindrical lens"], correctAnswerIndex: 0 },
      { id: 2009, question: "The 'Dronacharya Award' is associated with:", options: ["Eminent Surgeons", "Famous Artists", "Sports Coaches", "Expert Engineers"], correctAnswerIndex: 2 },
      { id: 2010, question: "What is the chemical name of 'Baking Soda'?", options: ["Sodium Carbonate", "Sodium Bicarbonate", "Calcium Carbonate", "Sodium Chloride"], correctAnswerIndex: 1 },
      { id: 2011, question: "Which Amendment of the Constitution of India added the word 'Secular' in the Preamble?", options: ["44th Amendment", "42nd Amendment", "52nd Amendment", "24th Amendment"], correctAnswerIndex: 1 },
      { id: 2012, question: "The study of insects is known as:", options: ["Ornithology", "Entomology", "Herpetology", "Ichthyology"], correctAnswerIndex: 1 },
      { id: 2013, question: "Which of the following is the largest gland in the human body?", options: ["Pancreas", "Liver", "Salivary gland", "Thyroid"], correctAnswerIndex: 1 },
      { id: 2014, question: "The book 'India Wins Freedom' was written by:", options: ["Jawaharlal Nehru", "Mahatma Gandhi", "Maulana Abul Kalam Azad", "Sardar Patel"], correctAnswerIndex: 2 },
      { id: 2015, question: "The headquarters of the World Trade Organization (WTO) is located in:", options: ["New York", "Geneva", "Paris", "London"], correctAnswerIndex: 1 },
      { id: 2016, question: "The term 'Satyameva Jayate' is taken from which Upanishad?", options: ["Mandukya Upanishad", "Mundaka Upanishad", "Katha Upanishad", "Chandogya Upanishad"], correctAnswerIndex: 1 },
      { id: 2017, question: "Which of the following Schedules of the Constitution of India contains provisions regarding anti-defection?", options: ["Second Schedule", "Fifth Schedule", "Eighth Schedule", "Tenth Schedule"], correctAnswerIndex: 3 },
      { id: 2018, question: "The famous 'Nalanda University' was founded during the reign of which ruler?", options: ["Chandragupta I", "Samudragupta", "Kumaragupta I", "Skandagupta"], correctAnswerIndex: 2 },
      { id: 2019, question: "What is the unit of electrical resistance?", options: ["Volt", "Ampere", "Ohm", "Watt"], correctAnswerIndex: 2 },
      { id: 2020, question: "The 'Chipko Movement' is related to:", options: ["Forest Conservation", "Water Conservation", "Soil Conservation", "Wildlife Protection"], correctAnswerIndex: 0 },
      { id: 2021, question: "Which planet in our solar system is known as the 'Morning Star' or 'Evening Star'?", options: ["Mars", "Jupiter", "Venus", "Mercury"], correctAnswerIndex: 2 },
      { id: 2022, question: "Who is known as the 'Father of the Indian Constitution'?", options: ["Mahatma Gandhi", "Dr. B. R. Ambedkar", "Jawaharlal Nehru", "Sardar Vallabhbhai Patel"], correctAnswerIndex: 1 },
      { id: 2023, question: "What is the pH value of pure water?", options: ["5", "7", "9", "1"], correctAnswerIndex: 1 },
      { id: 2024, question: "The 'Kailasa Temple' at Ellora was built by the rulers of which dynasty?", options: ["Chalukya", "Chola", "Pallava", "Rashtrakuta"], correctAnswerIndex: 3 },
      { id: 2025, question: "The dance form 'Kuchipudi' originated from which state of India?", options: ["Tamil Nadu", "Kerala", "Andhra Pradesh", "Karnataka"], correctAnswerIndex: 2 },
      { id: 2026, question: "The Radcliffe Line is the international border between which two countries?", options: ["India and China", "India and Pakistan", "India and Nepal", "India and Bangladesh"], correctAnswerIndex: 1 },
      { id: 2027, question: "Which gas is filled in electric bulbs to prevent the oxidation of the filament?", options: ["Oxygen", "Hydrogen", "Nitrogen", "Carbon Dioxide"], correctAnswerIndex: 2 },
      { id: 2028, question: "Who was the first Indian woman to climb Mount Everest?", options: ["Bachendri Pal", "Santosh Yadav", "Arunima Sinha", "Premlata Agarwal"], correctAnswerIndex: 0 },
      { id: 2029, question: "The 'Panchsheel' agreement was signed between India and which country?", options: ["Pakistan", "Nepal", "China", "Sri Lanka"], correctAnswerIndex: 2 },
      { id: 2030, question: "Which of the following is not a member of the G-7?", options: ["Canada", "France", "Russia", "Italy"], correctAnswerIndex: 2 },
    ];
    const q = questions[i % questions.length];
    return {
      ...q,
      id: 2001 + i,
      subject: 'General Studies',
      exam: 'SSC CGL',
      translation: {
        question: `यह ${q.id + i} के लिए एक अनुवादित प्रश्न है।`,
        options: q.options.map(o => `${o} का अनुवाद`)
      }
    };
  }),

  // --- Reasoning (Harder) - 250 questions ---
  ...Array.from({ length: 250 }, (_, i) => {
    const questions = [
      { id: 3001, question: "Find the next number in the series: 3, 7, 23, 95, ?", options: ["479", "383", "575", "475"], correctAnswerIndex: 0 },
      { id: 3002, question: "In a certain code, 'JOURNEY' is written as 'LPVSIDZ'. How is 'MEDICAL' written in that code?", options: ["NFHDJBK", "NFFDJBK", "NFDHDBK", "NFHDJCK"], correctAnswerIndex: 0 },
      { id: 3003, question: "Statements: All pens are pencils. No pencil is an eraser. Conclusions: I. No pen is an eraser. II. Some erasers are pens.", options: ["Only I follows", "Only II follows", "Both follow", "Neither follows"], correctAnswerIndex: 0 },
      { id: 3004, question: "Find the odd one out: 6, 12, 21, 32", options: ["6", "12", "21", "32"], correctAnswerIndex: 3 },
      { id: 3005, question: "If A is the brother of B, B is the sister of C, and C is the father of D, how is D related to A?", options: ["Brother", "Sister", "Nephew", "Cannot be determined"], correctAnswerIndex: 3 },
      { id: 3006, question: "Arrange the words in a meaningful sequence: 1. Police 2. Punishment 3. Crime 4. Judge 5. Judgment", options: ["3, 1, 4, 5, 2", "3, 1, 2, 4, 5", "3, 1, 5, 4, 2", "1, 2, 4, 5, 3"], correctAnswerIndex: 0 },
      { id: 3007, question: "Find the missing character: A, D, I, P, ?", options: ["W", "X", "Y", "Z"], correctAnswerIndex: 2 },
      { id: 3008, question: "Ravi walked 10 km North, then turned right and walked 5 km. Then he turned right and walked 10 km. In which direction is he from the starting point?", options: ["North", "South", "East", "West"], correctAnswerIndex: 2 },
      { id: 3009, question: "If 'pen' is 'table', 'table' is 'fan', 'fan' is 'chair' and 'chair' is 'roof', then on which of the following will a person sit?", options: ["Fan", "Chair", "Roof", "Table"], correctAnswerIndex: 2 },
      { id: 3010, question: "Find the mirror image of the word 'QUALITY'.", options: ["YTILAUQ", "YΤILAUQ", "QALITYU", "YTIALUQ"], correctAnswerIndex: 0 },
      { id: 3011, question: "Select the related word/letters/number from the given alternatives: Ornithologist : Bird :: Archaeologist : ?", options: ["Islands", "Archaeology", "Aquatic", "Mediators"], correctAnswerIndex: 1 },
      { id: 3012, question: "Which one of the given responses would be a meaningful order of the following? 1. Infant 2. Adult 3. Adolescent 4. Child", options: ["1, 4, 3, 2", "1, 3, 4, 2", "2, 3, 4, 1", "4, 3, 2, 1"], correctAnswerIndex: 0 },
      { id: 3013, question: "From the given alternative words, select the word which cannot be formed using the letters of the given word: 'CONSTITUTIONAL'", options: ["TALENT", "CONSULT", "LOCATION", "TUTION"], correctAnswerIndex: 0 },
      { id: 3014, question: "If '+' means '÷', '÷' means '-', '-' means '×' and '×' means '+', then 12 + 6 ÷ 3 - 2 × 8 = ?", options: ["-2", "2", "4", "8"], correctAnswerIndex: 2 },
      { id: 3015, question: "How many triangles are there in the given figure?", options: ["10", "12", "14", "16"], correctAnswerIndex: 3 },
      { id: 3016, question: "A, B, C, D, E and F are sitting in a circle facing the center. D is between F and B. A is second to the left of D and second to the right of E. Who is facing A?", options: ["B", "F", "D", "B or F"], correctAnswerIndex: 3 },
      { id: 3017, question: "Find the number which when added to itself 13 times, gives 112.", options: ["7", "8", "9", "11"], correctAnswerIndex: 1 },
      { id: 3018, question: "A watch reads 4:30. If the minute hand points East, in what direction will the hour hand point?", options: ["North-East", "South-East", "North", "South"], correctAnswerIndex: 0 },
      { id: 3019, question: "Select the figure which is different from the other three.", options: ["Figure A", "Figure B", "Figure C", "Figure D"], correctAnswerIndex: 2 },
      { id: 3020, question: "Statement: Should there be a ban on product advertising? Arguments: I. No. It is an age of advertising. Unless you advertise, your product will not be known. II. Yes. The money spent on advertising is huge and it inflates the cost of the product.", options: ["Only argument I is strong", "Only argument II is strong", "Either I or II is strong", "Both I and II are strong"], correctAnswerIndex: 3 },
      { id: 3021, question: "Find the next term in the series: B2E, D5H, F12K, H27N, ?", options: ["J58Q", "J56Q", "I58Q", "J58R"], correctAnswerIndex: 0 },
      { id: 3022, question: "A is D's brother. D is B's father. B and C are sisters. How is C related to A?", options: ["Cousin", "Niece", "Aunt", "Nephew"], correctAnswerIndex: 1 },
      { id: 3023, question: "If FRIEND is coded as HUMJTK, how is CANDLE written in that code?", options: ["EDRIRL", "DCQHQK", "ESJFME", "DEQJQM"], correctAnswerIndex: 0 },
      { id: 3024, question: "If it was a Saturday on 1st January 2000, what was the day of the week on 1st January 2001?", options: ["Sunday", "Monday", "Tuesday", "Wednesday"], correctAnswerIndex: 1 },
      { id: 3025, question: "Which of the following diagrams indicates the best relation between Travelers, Train and Bus?", options: ["Diagram A", "Diagram B", "Diagram C", "Diagram D"], correctAnswerIndex: 1 },
    ];
    const q = questions[i % questions.length];
    return { ...q, id: 3001 + i, subject: 'Reasoning', exam: 'SSC CGL' };
  }),

  // --- English (Harder) - 250 questions ---
  ...Array.from({ length: 250 }, (_, i) => {
    const questions = [
      { id: 4001, question: "Find the synonym of 'Cacophony'.", options: ["Harmony", "Silence", "Discord", "Melody"], correctAnswerIndex: 2 },
      { id: 4002, question: "Choose the correct meaning of the idiom 'To throw down the gauntlet'.", options: ["To accept defeat", "To give a challenge", "To surrender", "To abuse someone"], correctAnswerIndex: 1 },
      { id: 4003, question: "In the following question, a sentence has been given in Active/Passive voice. Out of the four alternatives, select the one which best expresses the same sentence in Passive/Active voice: 'The deputy manager is threatening the staff.'", options: ["The staff is threatened by the deputy manager.", "The staff are being threatened by the deputy manager.", "The deputy manager is being threatened by the staff.", "The staff were threatened by the deputy manager."], correctAnswerIndex: 1 },
      { id: 4004, question: "Find the antonym of 'Esoteric'.", options: ["Commonplace", "Mysterious", "Profound", "Secret"], correctAnswerIndex: 0 },
      { id: 4005, question: "Select the most appropriate word to fill in the blank: The student was punished for his ____.", options: ["imprudence", "impudence", "prudence", "insolence"], correctAnswerIndex: 1 },
      { id: 4006, question: "One who walks in sleep is called:", options: ["Somnambulist", "Altruist", "Egoist", "Somniloquist"], correctAnswerIndex: 0 },
      { id: 4007, question: "Find the correctly spelt word.", options: ["Connoiseur", "Connoisseur", "Connoisure", "Conoisseur"], correctAnswerIndex: 1 },
      { id: 4008, question: "Improve the bracketed part of the sentence: He (is having) a large family to support.", options: ["has", "have", "had", "No improvement"], correctAnswerIndex: 0 },
      { id: 4009, question: "Select the meaning of the idiom 'A chip on your shoulder'.", options: ["Having a grudge or grievance", "Carrying a heavy burden", "Being proud of oneself", "Having a piece of wood on shoulder"], correctAnswerIndex: 0 },
      { id: 4010, question: "In the sentence, identify the segment which contains the grammatical error: Neither the students nor the teacher were in his class.", options: ["Neither the students", "nor the teacher", "were in his class", "No error"], correctAnswerIndex: 2 },
      { id: 4011, question: "Select the synonym of 'Garrulous'.", options: ["Taciturn", "Reticent", "Concise", "Talkative"], correctAnswerIndex: 3 },
      { id: 4012, question: "Select the antonym of 'Procrastinate'.", options: ["Delay", "Postpone", "Expedite", "Defer"], correctAnswerIndex: 2 },
      { id: 4013, question: "Choose the word that can substitute the given group of words: A person who is indifferent to pains and pleasures of life.", options: ["Stoic", "Ascetic", "Cynic", "Psychic"], correctAnswerIndex: 0 },
      { id: 4014, question: "Select the most appropriate option to change the narration (direct/indirect): He said to me, 'I have often told you not to play with fire.'", options: ["He told me that he had often told me not to play with fire.", "He reminded me that he had often told me not to play with fire.", "He said to me that he has often told me not to play with fire.", "He told to me that he had often told me not to play with fire."], correctAnswerIndex: 1 },
      { id: 4015, question: "Find the part of the given sentence that has an error in it. If there is no error, choose 'No error'.: It is high time / he stood on his own / two legs.", options: ["It is high time", "he stood on his own", "two legs", "No error"], correctAnswerIndex: 3 },
      { id: 4016, question: "Fill in the blank: The higher you go, the more difficult it ____ to breathe.", options: ["is becoming", "becomes", "has become", "will become"], correctAnswerIndex: 1 },
      { id: 4017, question: "Choose the correct meaning of the idiom: 'Bite the bullet'", options: ["To eat something hard", "To endure a difficult situation", "To enjoy a meal", "To die"], correctAnswerIndex: 1 },
      { id: 4018, question: "Find the correctly spelt word.", options: ["Embarassment", "Embarrassment", "Embarasment", "Embarrasment"], correctAnswerIndex: 1 },
      { id: 4019, question: "A government by the nobles/lords is called:", options: ["Democracy", "Autocracy", "Aristocracy", "Bureaucracy"], correctAnswerIndex: 2 },
      { id: 4020, question: "Select the synonym for 'Ephemeral'.", options: ["Permanent", "Eternal", "Transient", "Lasting"], correctAnswerIndex: 2 },
      { id: 4021, question: "Select the antonym for 'Venerate'.", options: ["Revere", "Respect", "Despise", "Honor"], correctAnswerIndex: 2 },
      { id: 4022, question: "Improve the bracketed part of the sentence: Scarcely (I had arrived) than the train left.", options: ["had I arrived", "I arrived", "did I arrive", "No improvement"], correctAnswerIndex: 0 },
      { id: 4023, question: "Select the most appropriate word to fill in the blank: His _____ nature would not let him leave the workplace.", options: ["conscientious", "conscious", "consecutive", "consensus"], correctAnswerIndex: 0 },
      { id: 4024, question: "Select the most appropriate option to change the narration (direct/indirect): The teacher said, 'Be quiet, boys.'", options: ["The teacher told the boys to be quiet.", "The teacher called the boys and ordered them to be quiet.", "The teacher urged the boys to be quiet.", "The teacher commanded the boys that they be quiet."], correctAnswerIndex: 2 },
      { id: 4025, question: "Find the part of the given sentence that has an error in it. If there is no error, choose 'No error'.: The reason why / he was rejected / was because he was too young.", options: ["The reason why", "he was rejected", "was because he was too young", "No error"], correctAnswerIndex: 2 },
    ];
    const q = questions[i % questions.length];
    return { ...q, id: 4001 + i, subject: 'English', exam: 'SSC CGL' };
  }),
];
