import { Question } from '../types';

export const chslQuestions: Question[] = [
  // --- Maths (Moderate) ---
  // Number System (10)
  { id: 11001, question: "What is the largest 4-digit number exactly divisible by 88?", options: ["9944", "9900", "9988", "8888"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'number-system' },
  { id: 11002, question: "The sum of two numbers is 40 and their product is 375. What will be the sum of their reciprocals?", options: ["8/75", "1/40", "75/8", "75/4"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'number-system' },
  { id: 11003, question: "Find the unit digit in the product (2467)^153 * (341)^72.", options: ["1", "3", "7", "9"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'number-system' },
  { id: 11004, question: "A number when divided by 6 leaves a remainder 3. When the square of the same number is divided by 6, the remainder is:", options: ["0", "1", "2", "3"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CHSL', chapter: 'number-system' },
  { id: 11005, question: "The HCF of two numbers is 23 and their LCM is 1449. If one of the numbers is 161, the other is:", options: ["207", "307", "187", "227"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'number-system' },
  { id: 11006, question: "Which of the following is a prime number?", options: ["117", "147", "177", "197"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CHSL', chapter: 'number-system' },
  { id: 11007, question: "The value of 5 + [4 - (6 - 2 - 1)] is:", options: ["5", "4", "3", "2"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'number-system' },
  { id: 11008, question: "If a number is divisible by both 11 and 13, then it must be necessarily divisible by:", options: ["11+13", "13-11", "11*13", "None of these"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'number-system' },
  { id: 11009, question: "Find the sum of first 30 natural numbers.", options: ["465", "455", "475", "485"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'number-system' },
  { id: 11010, question: "What is the local value of 7 in the numeral 657982?", options: ["7000", "700", "70", "7"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'number-system' },

  // Percentages (10)
  { id: 11011, question: "If 15% of a number is 45, what is 30% of the number?", options: ["60", "90", "75", "100"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'percentages' },
  { id: 11012, question: "A man spends 75% of his income. If his income increases by 20% and his expenditure increases by 10%, his savings will be increased by:", options: ["40%", "50%", "30%", "25%"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'percentages' },
  { id: 11013, question: "In a class of 60 students, 45% are girls. The number of boys in the class is:", options: ["27", "33", "30", "25"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'percentages' },
  { id: 11014, question: "A number exceeds 20% of itself by 40. The number is:", options: ["50", "60", "80", "48"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'percentages' },
  { id: 11015, question: "What percent of 2/7 is 1/35?", options: ["10%", "20%", "25%", "5%"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'percentages' },
  { id: 11016, question: "If the price of a commodity is decreased by 20% and its consumption is increased by 20%, what will be the increase or decrease in expenditure on the commodity?", options: ["4% decrease", "4% increase", "8% decrease", "No change"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'percentages' },
  { id: 11017, question: "Fresh fruit contains 68% water and dry fruit contains 20% water. How much dry fruit can be obtained from 100 kg of fresh fruits?", options: ["32 kg", "40 kg", "52 kg", "80 kg"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'percentages' },
  { id: 11018, question: "The value of a machine depreciates at the rate of 10% every year. It was purchased 3 years ago. If its present value is Rs. 8748, its purchase price was:", options: ["Rs. 10000", "Rs. 11372.40", "Rs. 12000", "Rs. 12500"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'percentages' },
  { id: 11019, question: "In an examination, 35% of the candidates failed in one subject and 42% failed in another subject while 15% failed in both the subjects. If 2500 candidates appeared at the examination, how many passed in either subject but not in both?", options: ["1550", "1600", "1175", "1325"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'percentages' },
  { id: 11020, question: "A man's salary is first increased by 50% and then decreased by 50%. What is the percentage change in his salary?", options: ["25% decrease", "25% increase", "No change", "50% decrease"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'percentages' },
  
  // Ratio and Proportion (10)
  { id: 11021, question: "If A:B = 3:4 and B:C = 8:9, then A:C is equal to:", options: ["1:3", "3:2", "2:3", "1:2"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'ratio-proportion' },
  { id: 11022, question: "The fourth proportional to 5, 8, 15 is:", options: ["18", "24", "19", "20"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'ratio-proportion' },
  { id: 11023, question: "A sum of Rs. 312 was divided among 100 boys and girls in such a way that each boy gets Rs. 3.60 and each girl Rs. 2.40. The number of girls is:", options: ["40", "45", "35", "50"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'ratio-proportion' },
  { id: 11024, question: "If x:y = 3:4, find the value of (4x + 5y) : (5x - 2y).", options: ["32:7", "8:7", "7:32", "7:8"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'ratio-proportion' },
  { id: 11025, question: "Two numbers are in the ratio 1:2. If 7 is added to both, their ratio changes to 3:5. The greatest number is:", options: ["24", "26", "28", "32"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'ratio-proportion' },
  { id: 11026, question: "The salaries of A, B, and C are in the ratio 1:3:4. If their salaries are increased by 5%, 10%, and 15% respectively, then the increased salaries will be in the ratio:", options: ["20:66:95", "21:66:92", "21:66:95", "20:60:92"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'ratio-proportion' },
  { id: 11027, question: "What number has to be added to each term of 3:5 to make the ratio 5:6?", options: ["6", "7", "12", "11"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'ratio-proportion' },
  { id: 11028, question: "A mixture of 40 liters of milk and water contains 10% water. How much water should be added to this mixture so that the new mixture contains 20% water?", options: ["5 liters", "4 liters", "6.5 liters", "7.5 liters"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'ratio-proportion' },
  { id: 11029, question: "The third proportional to 16 and 36 is:", options: ["81", "72", "64", "52"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'ratio-proportion' },
  { id: 11030, question: "Seats for Mathematics, Physics and Biology in a school are in the ratio 5:7:8. There is a proposal to increase these seats by 40%, 50% and 75% respectively. What will be the ratio of increased seats?", options: ["2:3:4", "6:7:8", "6:8:9", "None of these"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'ratio-proportion' },

  // Averages (10)
  { id: 11031, question: "The average of first 10 even numbers is:", options: ["10", "11", "12", "13"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'averages' },
  { id: 11032, question: "The average of 5 consecutive odd numbers is 17. Find the largest number.", options: ["19", "21", "23", "17"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'averages' },
  { id: 11033, question: "The average of 3 numbers is 77. The first number is twice the second and the second number is twice the third. The first number is:", options: ["33", "66", "77", "132"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CHSL', chapter: 'averages' },
  { id: 11034, question: "The average of 10 numbers is 7. If each number is multiplied by 12, then the average of the new set of numbers is:", options: ["7", "19", "82", "84"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CHSL', chapter: 'averages' },
  { id: 11035, question: "A cricketer has a certain average for 10 innings. In the eleventh inning, he scored 108 runs, thereby increasing his average by 6 runs. His new average is:", options: ["48", "52", "55", "60"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'averages' },
  { id: 11036, question: "The average weight of 8 persons increases by 2.5 kg when a new person comes in place of one of them weighing 65 kg. What might be the weight of the new person?", options: ["76 kg", "76.5 kg", "85 kg", "80 kg"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'averages' },
  { id: 11037, question: "The average of 7 consecutive numbers is 20. The largest of these numbers is:", options: ["20", "22", "23", "24"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'averages' },
  { id: 11038, question: "The average of the first nine prime numbers is:", options: ["9", "11", "11 1/9", "11 2/9"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'averages' },
  { id: 11039, question: "The average age of a family of 5 members is 24 years. If the present age of the youngest member is 8 years, what was the average age of the family at the time of the birth of the youngest member?", options: ["16 years", "18 years", "20 years", "22 years"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'averages' },
  { id: 11040, question: "The average of five numbers is 27. If one number is excluded, the average becomes 25. The excluded number is:", options: ["25", "27", "30", "35"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CHSL', chapter: 'averages' },

  // Simple and Compound Interest (10)
  { id: 11041, question: "Find the simple interest on Rs. 68,000 at 16 2/3% per annum for 9 months.", options: ["Rs. 8500", "Rs. 8000", "Rs. 9000", "Rs. 9500"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'si-ci' },
  { id: 11042, question: "A sum of money doubles itself at compound interest in 15 years. In how many years will it become eight times?", options: ["30 years", "45 years", "50 years", "60 years"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'si-ci' },
  { id: 11043, question: "Find the compound interest on Rs. 16,000 at 20% per annum for 9 months, compounded quarterly.", options: ["Rs. 2522", "Rs. 2500", "Rs. 2480", "Rs. 2600"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'si-ci' },
  { id: 11044, question: "A sum of money invested at compound interest amounts to Rs. 800 in 2 years and Rs. 840 in 3 years. The rate of interest per annum is:", options: ["4%", "5%", "6%", "8%"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'si-ci' },
  { id: 11045, question: "How much time will it take for an amount of Rs. 450 to yield Rs. 81 as interest at 4.5% per annum of simple interest?", options: ["3.5 years", "4 years", "4.5 years", "5 years"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'si-ci' },
  { id: 11046, question: "The difference between CI and SI on a certain sum for 2 years at 10% per annum is Rs. 40. The sum is:", options: ["Rs. 4000", "Rs. 3000", "Rs. 2000", "Rs. 2500"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'si-ci' },
  { id: 11047, question: "A sum of money becomes 4 times in 2 years at CI. In how many years it will be 16 times?", options: ["2 years", "4 years", "6 years", "8 years"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'si-ci' },
  { id: 11048, question: "A man took a loan from a bank at the rate of 12% p.a. simple interest. After 3 years he had to pay Rs. 5400 interest only for the period. The principal amount borrowed by him was:", options: ["Rs. 2000", "Rs. 10,000", "Rs. 15,000", "Rs. 20,000"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'si-ci' },
  { id: 11049, question: "The simple interest on a sum of money is 4/9 of the principal. Find the rate percent and time, if both are numerically equal.", options: ["6 2/3", "7 1/3", "5 2/3", "6"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'si-ci' },
  { id: 11050, question: "What will be the compound interest on Rs. 25,000 for 2 years at 12% per annum?", options: ["Rs. 6360", "Rs. 6000", "Rs. 6250", "Rs. 6500"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'si-ci' },

  // Profit, Loss and Discount (10)
  { id: 11051, question: "A shopkeeper sells a transistor for Rs. 840 at a gain of 20%. and another for Rs. 960 at a loss of 4%. His total gain or loss percent is:", options: ["5 15/17% loss", "5 15/17% gain", "6 2/3% gain", "6% loss"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'profit-loss-discount' },
  { id: 11052, question: "An article is sold at a certain price. By selling it at 2/3 of that price, one loses 10%. The gain percent at original price is:", options: ["20%", "33 1/3%", "35%", "40%"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'profit-loss-discount' },
  { id: 11053, question: "The percentage profit earned by selling an article for Rs. 1920 is equal to the percentage loss incurred by selling the same article for Rs. 1280. At what price should the article be sold to make 25% profit?", options: ["Rs. 2000", "Rs. 2200", "Rs. 2400", "Data inadequate"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'profit-loss-discount' },
  { id: 11054, question: "A trader mixes 26 kg of rice at Rs. 20 per kg with 30 kg of rice of other variety at Rs. 36 per kg and sells the mixture at Rs. 30 per kg. His profit percent is:", options: ["No profit, no loss", "5%", "8%", "10%"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'profit-loss-discount' },
  { id: 11055, question: "A shopkeeper allows a discount of 10% to his customers and still gains 20%. Find the marked price of the article which costs Rs. 450.", options: ["Rs. 500", "Rs. 550", "Rs. 600", "Rs. 650"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'profit-loss-discount' },
  { id: 11056, question: "By selling an article for Rs. 240, a man incurs a loss of 10%. At what price should he sell it so that he makes a profit of 20%?", options: ["Rs. 264", "Rs. 288", "Rs. 300", "Rs. 320"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CHSL', chapter: 'profit-loss-discount' },
  { id: 11057, question: "A man bought some fruits at the rate of 16 for Rs. 24 and sold them at the rate of 8 for Rs. 18. What is the profit percent?", options: ["25%", "40%", "50%", "60%"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'profit-loss-discount' },
  { id: 11058, question: "On selling 17 balls at Rs. 720, there is a loss equal to the cost price of 5 balls. The cost price of a ball is:", options: ["Rs. 45", "Rs. 50", "Rs. 55", "Rs. 60"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CHSL', chapter: 'profit-loss-discount' },
  { id: 11059, question: "When a plot is sold for Rs. 18,700, the owner loses 15%. At what price must that plot be sold in order to gain 15%?", options: ["Rs. 21,000", "Rs. 22,500", "Rs. 25,300", "Rs. 25,800"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'profit-loss-discount' },
  { id: 11060, question: "A trader sells his goods at a discount of 20%. He still makes a profit of 25%. If he sells the goods at the marked price only, his profit will be:", options: ["56.25%", "25%", "50%", "54%"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'profit-loss-discount' },

  // Mixtures and Allegations (10)
  { id: 11061, question: "A grocer wishes to sell a mixture of two varieties of pulses worth Rs. 16 per kg. In what ratio must he mix the pulses to make a profit of 10% if one variety costs Rs. 14 per kg and the other Rs. 24 per kg?", options: ["7:3", "7:2", "8:3", "8:1"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CHSL', chapter: 'mixtures-allegations' },
  { id: 11062, question: "A mixture of certain quantity of milk with 16 litres of water is worth 90 P per litre. If pure milk be worth Rs. 1.08 per litre, how much milk is there in the mixture?", options: ["40 litres", "60 litres", "80 litres", "100 litres"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'mixtures-allegations' },
  { id: 11063, question: "A 20 litre mixture of milk and water contains milk and water in the ratio 3 : 2. 10 litres of the mixture is removed and replaced with pure milk. The ratio of milk and water in the new mixture is:", options: ["7:3", "9:1", "11:1", "13:1"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'mixtures-allegations' },
  { id: 11064, question: "A vessel contains 60 litres of a mixture of milk and water in the ratio 2 : 1. How much water must be added to it so that the ratio of milk to water becomes 1 : 2?", options: ["40 litres", "50 litres", "60 litres", "70 litres"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'mixtures-allegations' },
  { id: 11065, question: "In what ratio must water be mixed with milk, costing Rs. 12 per litre, to obtain a mixture worth of Rs. 8 per litre?", options: ["1:2", "2:1", "2:3", "3:2"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'mixtures-allegations' },
  { id: 11066, question: "A jar full of whisky contains 40% alcohol. A part of this whisky is replaced by another containing 19% alcohol and now the percentage of alcohol was found to be 26%. The quantity of whisky replaced is:", options: ["1/3", "2/3", "2/5", "3/5"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'mixtures-allegations' },
  { id: 11067, question: "A merchant has 1000 kg of sugar, part of which he sells at 8% profit and the rest at 18% profit. He gains 14% on the whole. The quantity sold at 18% profit is:", options: ["400 kg", "560 kg", "600 kg", "640 kg"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'mixtures-allegations' },
  { id: 11068, question: "A container has a capacity of 100 litres and is full of milk. 10 litres of milk is drawn out and replaced with water. This process is repeated 2 more times. Find the quantity of milk left in the container.", options: ["70 litres", "72.9 litres", "81 litres", "75 litres"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'mixtures-allegations' },
  { id: 11069, question: "How many liters of water should be added to a 30-liter mixture of milk and water containing milk and water in the ratio 7:3 such that the resultant mixture has 40% water in it?", options: ["5", "6", "7", "8"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'mixtures-allegations' },
  { id: 11070, question: "A mixture of 66 L of milk and water are in the ratio 5:1. Water is added to it to make the ratio 5:3. The quantity of water added is:", options: ["22 L", "24 L", "20 L", "25 L"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'mixtures-allegations' },

  // Time and Work (10)
  { id: 11071, question: "A can do a piece of work in 10 days, while B can do it in 15 days. They work together for 5 days. The rest of the work is finished by C in 2 days. If they get Rs. 150 for the whole work, the daily wages of B and C are:", options: ["Rs. 15", "Rs. 20", "Rs. 25", "Rs. 30"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'time-work' },
  { id: 11072, question: "A can do a work in 25 days and B can do the same work in 20 days. They work together for 5 days and then A goes away. In how many days will B finish the remaining work?", options: ["17 days", "11 days", "10 days", "15 days"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'time-work' },
  { id: 11073, question: "A and B can do a piece of work in 12 days, B and C in 15 days, C and A in 20 days. How long would B take to do the same work?", options: ["20 days", "30 days", "40 days", "60 days"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'time-work' },
  { id: 11074, question: "A works twice as fast as B. If B can complete a work in 12 days independently, the number of days in which A and B can together finish the work is:", options: ["4 days", "6 days", "8 days", "18 days"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'time-work' },
  { id: 11075, question: "Two pipes can fill a tank in 10 hours and 12 hours respectively. A third pipe can empty the tank in 20 hours. If all the three pipes are opened together, then the tank will be filled in:", options: ["5 hrs", "7.5 hrs", "8 hrs", "8.5 hrs"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'time-work' },
  { id: 11076, question: "If 16 men or 20 women can do a piece of work in 25 days. In what time will 28 men and 15 women do it?", options: ["14 2/7 days", "33 1/3 days", "18 3/4 days", "10 days"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CHSL', chapter: 'time-work' },
  { id: 11077, question: "A can finish a work in 24 days, B in 9 days and C in 12 days. B and C start the work but are forced to leave after 3 days. The remaining work was done by A in:", options: ["5 days", "6 days", "10 days", "10.5 days"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'time-work' },
  { id: 11078, question: "A is 30% more efficient than B. How much time will they, working together, take to complete a job which A alone could have done in 23 days?", options: ["11 days", "13 days", "20 3/10 days", "None of these"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'time-work' },
  { id: 11079, question: "A pipe can fill a tank in 15 minutes and another one in 10 minutes. A third pipe can empty the tank in 5 minutes. The first two pipes are kept open for 4 minutes in the beginning and then the third pipe is also opened. In what time is the tank emptied?", options: ["35 min", "15 min", "20 min", "Can't be emptied"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'time-work' },
  { id: 11080, question: "A and B can do a piece of work in 30 days, while B and C can do the same work in 24 days and C and A in 20 days. They all work together for 10 days when B and C leave. How many days more will A take to finish the work?", options: ["18 days", "24 days", "30 days", "36 days"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'time-work' },

  // Time, Speed and Distance (10)
  { id: 11081, question: "A car covers a distance of 816 km in 12 hours. What is the speed of the car?", options: ["64 km/hr", "66 km/hr", "68 km/hr", "Cannot be determined"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'time-speed-distance' },
  { id: 11082, question: "A train 125 m long passes a man, running at 5 km/hr in the same direction in which the train is going, in 10 seconds. The speed of the train is:", options: ["45 km/hr", "50 km/hr", "54 km/hr", "55 km/hr"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'time-speed-distance' },
  { id: 11083, question: "A man completes a journey in 10 hours. He travels first half of the journey at the rate of 21 km/hr and second half at the rate of 24 km/hr. Find the total journey in km.", options: ["220 km", "224 km", "230 km", "234 km"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'time-speed-distance' },
  { id: 11084, question: "The ratio between the speeds of two trains is 7 : 8. If the second train runs 400 km in 4 hours, then the speed of the first train is:", options: ["70 km/hr", "75 km/hr", "84 km/hr", "87.5 km/hr"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CHSL', chapter: 'time-speed-distance' },
  { id: 11085, question: "A train passes a station platform in 36 seconds and a man standing on the platform in 20 seconds. If the speed of the train is 54 km/hr, what is the length of the platform?", options: ["120 m", "240 m", "300 m", "None of these"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'time-speed-distance' },
  { id: 11086, question: "In a flight of 600 km, an aircraft was slowed down due to bad weather. Its average speed for the trip was reduced by 200 km/hr and the time of flight increased by 30 minutes. The duration of the flight is:", options: ["1 hour", "2 hours", "3 hours", "4 hours"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'time-speed-distance' },
  { id: 11087, question: "A man can row at 5 kmph in still water. If the velocity of current is 1 kmph and it takes him 1 hour to row to a place and come back, how far is the place?", options: ["2.4 km", "2.5 km", "3 km", "3.6 km"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'time-speed-distance' },
  { id: 11088, question: "A car travelling at a speed of 40 km/hr can complete a journey in 9 hours. How long will it take to travel the same distance at 60 km/hr?", options: ["6 hours", "5 hours", "4 hours", "3 hours"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'time-speed-distance' },
  { id: 11089, question: "A person travels from P to Q at a speed of 40 km/hr and returns by increasing his speed by 50%. What is his average speed for both the trips?", options: ["36 km/hr", "45 km/hr", "48 km/hr", "50 km/hr"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'time-speed-distance' },
  { id: 11090, question: "A train 100 m long is running at the speed of 30 km/hr. Find the time taken by it to pass a man standing near the railway line.", options: ["10 sec", "12 sec", "14 sec", "16 sec"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'time-speed-distance' },

  // Partnership (10)
  { id: 11091, question: "A and B start a business jointly. A invests Rs. 16,000 for 8 months and B remains in the business for 4 months. Out of a total profit, B claims 2/7 of the profit. How much money was contributed by B?", options: ["Rs. 10,500", "Rs. 11,200", "Rs. 12,800", "Rs. 13,600"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'partnership' },
  { id: 11092, question: "A, B and C enter into partnership. A invests 3 times as much as B invests and B invests two-third of what C invests. At the end of the year, the profit earned is Rs. 6600. What is the share of B?", options: ["Rs. 1200", "Rs. 1800", "Rs. 2400", "Rs. 3000"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'partnership' },
  { id: 11093, question: "Simran started a software business by investing Rs. 50,000. After six months, Nanda joined her with a capital of Rs. 80,000. After 3 years, they earned a profit of Rs. 24,500. What was Simran's share in the profit?", options: ["Rs. 9,423", "Rs. 10,250", "Rs. 12,500", "Rs. 14,000"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'partnership' },
  { id: 11094, question: "A, B, C start a business. A invests Rs. 320 for 4 months, B invests Rs. 510 for 3 months, and C invests Rs. 270 for 5 months. If the total profit is Rs. 208, find the share of C.", options: ["Rs. 60", "Rs. 67.50", "Rs. 72.50", "Rs. 80"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'partnership' },
  { id: 11095, question: "A and B are partners in a business. A invests Rs. 35,000 for 8 months and B invests Rs. 42,000 for 10 months. Out of a profit of Rs. 31,570, A's share is:", options: ["Rs. 12,628", "Rs. 13,500", "Rs. 14,728", "Rs. 15,200"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'partnership' },
  { id: 11096, question: "A and B start a business. A invests Rs. 600 more than B. The capital of B remained invested for 7.5 months, while the capital of A remained invested for 2.5 more months than B. If the total profit is Rs. 620 and the share of B is Rs. 200 less than that of A, find the capital of B.", options: ["Rs. 1800", "Rs. 2400", "Rs. 3000", "Rs. 3600"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'partnership' },
  { id: 11097, question: "A, B and C invest Rs. 13000, Rs. 17000 and Rs. 5000 respectively in a business. At the end of the year, they earn a profit of Rs. 1400. B's share of profit is:", options: ["Rs. 400", "Rs. 520", "Rs. 680", "Rs. 800"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'partnership' },
  { id: 11098, question: "P and Q started a business with Rs. 20,000 and Rs. 35,000 respectively. They agreed to share the profit in the ratio of their capital. C joins the partnership with the condition that P, Q and C will share profit equally and pays Rs. 2,20,000 as premium for this, to be distributed between P and Q. This is to be divided between P and Q in the ratio of", options: ["10:1", "1:10", "9:2", "2:9"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'partnership' },
  { id: 11099, question: "A starts business with Rs. 3500 and after 5 months, B joins with A as his partner. After a year, the profit is divided in the ratio 2 : 3. What is B's contribution in the capital?", options: ["Rs. 7500", "Rs. 8000", "Rs. 8500", "Rs. 9000"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CHSL', chapter: 'partnership' },
  { id: 11100, question: "A and B invest Rs. 3000 and Rs. 4000 in a business. A receives Rs. 10 per month out of the profit as a remuneration for running the business and the rest of the profit is divided in proportion to the investments. If in a year A totally receives Rs. 390, what does B receive?", options: ["Rs. 360", "Rs. 480", "Rs. 720", "Rs. 960"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'partnership' },

  // Algebra (10)
  { id: 11101, question: "If x + 1/x = 4, then find the value of x² + 1/x².", options: ["14", "16", "12", "18"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'algebra'},
  { id: 11102, question: "Find the factors of x² - 5x + 6.", options: ["(x-2)(x-3)", "(x+2)(x+3)", "(x-2)(x+3)", "(x+2)(x-3)"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'algebra'},
  { id: 11103, question: "If 2a - 3b = 3 and ab = 2, find the value of 4a² + 9b².", options: ["9", "21", "33", "45"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CHSL', chapter: 'algebra'},
  { id: 11104, question: "If x + y = 7 and xy = 12, then the value of x² + y² is:", options: ["25", "37", "49", "13"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'algebra'},
  { id: 11105, question: "The sum of the squares of three consecutive natural numbers is 110. The numbers are:", options: ["4, 5, 6", "5, 6, 7", "6, 7, 8", "3, 4, 5"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'algebra'},
  { id: 11106, question: "If (x - 2) is a factor of x² + kx + 4, then k = ?", options: ["-4", "4", "-3", "3"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'algebra'},
  { id: 11107, question: "What is the value of (999 + 99)²?", options: ["1195024", "1205604", "1185024", "1188064"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'algebra'},
  { id: 11108, question: "If a/3 = b/4 = c/7, then the value of (a+b+c)/c is:", options: ["1", "2", "3", "7"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'algebra'},
  { id: 11109, question: "Simplify: (x²-y²) / (x-y)", options: ["x-y", "x+y", "xy", "(x-y)²"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'algebra'},
  { id: 11110, question: "If x + 1/x = 2, then x¹⁰⁰ + 1/x¹⁰⁰ is equal to:", options: ["2", "1", "100", "200"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'algebra'},
  
  // Geometry (10)
  { id: 11201, question: "An exterior angle of a regular polygon is 72°. The number of sides is:", options: ["3", "4", "5", "6"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'geometry' },
  { id: 11202, question: "In a triangle ABC, if ∠A = 90°, AB = 5 cm and AC = 12 cm, then the length of the median AD is:", options: ["6.5 cm", "7 cm", "8 cm", "13 cm"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'geometry' },
  { id: 11203, question: "Two chords AB and CD of a circle intersect at E. If AE = 2.4, BE = 3.6, and CE = 3, then DE equals:", options: ["2.88", "1.8", "5.4", "4.5"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'geometry' },
  { id: 11204, question: "The distance between the centers of two equal circles, each of radius 3 cm, is 10 cm. The length of a transverse common tangent is:", options: ["4 cm", "6 cm", "8 cm", "10 cm"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'geometry' },
  { id: 11205, question: "If two angles of a triangle are 30° and 45°, what is the third angle?", options: ["75°", "90°", "105°", "120°"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'geometry' },
  { id: 11206, question: "The perimeter of a rhombus is 40 cm. If one of the diagonals is 12 cm long, what is the length of the other diagonal?", options: ["16 cm", "14 cm", "10 cm", "8 cm"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'geometry' },
  { id: 11207, question: "In a circle, a chord of length 16 cm is at a distance of 6 cm from the center. The radius of the circle is:", options: ["8 cm", "10 cm", "12 cm", "14 cm"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'geometry' },
  { id: 11208, question: "The angles of a quadrilateral are in the ratio 1:2:3:4. The smallest angle is:", options: ["36°", "45°", "72°", "90°"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'geometry' },
  { id: 11209, question: "Two parallel chords of a circle of radius 5 cm are on opposite sides of the center. If their lengths are 8 cm and 6 cm, the distance between them is:", options: ["7 cm", "8 cm", "9 cm", "10 cm"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'geometry' },
  { id: 11210, question: "The sum of the interior angles of a hexagon is:", options: ["360°", "540°", "720°", "900°"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'geometry' },

  // Trigonometry (10)
  { id: 11301, question: "If tan θ = 4/3, what is the value of sin θ?", options: ["4/5", "3/5", "3/4", "5/4"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'trigonometry' },
  { id: 11302, question: "The value of sin² 60° + cos² 60° is:", options: ["0", "1/2", "1", "2"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'trigonometry' },
  { id: 11303, question: "If sin A = 1/2, then the value of cot A is:", options: ["√3", "1/√3", "1", "0"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'trigonometry' },
  { id: 11304, question: "What is the value of (1 - tan² 45°) / (1 + tan² 45°)?", options: ["1", "0", "1/2", "Undefined"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'trigonometry' },
  { id: 11305, question: "If tan θ = 1, then the value of (sin θ + cos θ) / (sec θ + cosec θ) is:", options: ["1/2", "1", "2", "√2"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'trigonometry' },
  { id: 11306, question: "The angle of elevation of the sun, when the length of the shadow of a tree is √3 times the height of the tree, is:", options: ["30°", "45°", "60°", "75°"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'trigonometry' },
  { id: 11307, question: "The value of sin 75° is:", options: ["(√6 - √2)/4", "(√6 + √2)/4", "(√3 - 1)/2", "(√3 + 1)/2"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'trigonometry' },
  { id: 11308, question: "If sec θ + tan θ = 2, then the value of sec θ is:", options: ["5/4", "4/5", "3/4", "4/3"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'trigonometry' },
  { id: 11309, question: "The value of sec² θ - tan² θ is:", options: ["0", "1", "2", "-1"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'trigonometry' },
  { id: 11310, question: "cos 20° cos 40° cos 80° = ?", options: ["1/2", "1/4", "1/8", "1/16"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'trigonometry' },

  // Mensuration (10)
  { id: 11401, question: "The area of a square is 144 sq. cm. The perimeter of the square is:", options: ["12 cm", "24 cm", "36 cm", "48 cm"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CHSL', chapter: 'mensuration' },
  { id: 11402, question: "The length and breadth of a rectangle are in the ratio 3:2. If its perimeter is 100 m, find its area.", options: ["300 sq. m", "400 sq. m", "500 sq. m", "600 sq. m"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC CHSL', chapter: 'mensuration' },
  { id: 11403, question: "The radius of a circle is 7 cm. Its circumference is:", options: ["22 cm", "44 cm", "88 cm", "154 cm"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'mensuration' },
  { id: 11404, question: "The volume of a cube is 125 cm³. Its total surface area is:", options: ["100 cm²", "125 cm²", "150 cm²", "175 cm²"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'mensuration' },
  { id: 11405, question: "The area of a triangle with base 10 cm and height 5 cm is:", options: ["25 cm²", "50 cm²", "75 cm²", "100 cm²"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'mensuration' },
  { id: 11406, question: "The curved surface area of a cylinder with radius 7 cm and height 10 cm is:", options: ["220 cm²", "330 cm²", "440 cm²", "550 cm²"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'mensuration' },
  { id: 11407, question: "The volume of a sphere with radius 3 cm is:", options: ["12π cm³", "24π cm³", "36π cm³", "48π cm³"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'mensuration' },
  { id: 11408, question: "The perimeter of a rectangle is 60 cm. If its length is twice its breadth, find the length.", options: ["10 cm", "20 cm", "30 cm", "40 cm"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'mensuration' },
  { id: 11409, question: "The area of a right-angled triangle is 30 sq. cm. If its height is 7 cm more than its base, find the base.", options: ["5 cm", "8 cm", "10 cm", "12 cm"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'mensuration' },
  { id: 11410, question: "The volume of a cuboid is 216 cm³. If its dimensions are in the ratio 1:2:3, find the length of the longest side.", options: ["3 cm", "6 cm", "9 cm", "12 cm"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'mensuration' },

  // Statistics, Probability, DI, Coordinate Geometry (10)
  { id: 11501, question: "The mean of the numbers 1, 2, 3, 4, 5 is:", options: ["2", "3", "4", "5"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'statistics' },
  { id: 11502, question: "A coin is tossed. What is the probability of getting a head?", options: ["1", "1/2", "0", "2"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'probability' },
  { id: 11503, question: "Find the median of the data: 2, 5, 3, 1, 4.", options: ["3", "2", "1", "5"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'statistics' },
  { id: 11504, question: "The point (-3, -4) lies in which quadrant?", options: ["I", "II", "III", "IV"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'coordinate-geometry' },
  { id: 11505, question: "A die is thrown once. What is the probability of getting a prime number?", options: ["1/2", "1/3", "1/6", "2/3"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'probability' },
  { id: 11506, question: "Find the mode of the data: 1, 2, 2, 3, 3, 3, 4.", options: ["1", "2", "3", "4"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'statistics' },
  { id: 11507, question: "What is the distance between the points (0,0) and (3,4)?", options: ["3", "4", "5", "7"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC CHSL', chapter: 'coordinate-geometry' },
  { id: 11508, question: "From a well-shuffled deck of 52 cards, what is the probability of drawing an ace?", options: ["1/13", "1/26", "1/52", "4/13"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'probability' },
  { id: 11509, question: "The bar graph shows production of cars. What is the total production in 5 years? (Year1:20, Y2:30, Y3:25, Y4:40, Y5:35)", options: ["150", "160", "140", "155"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC CHSL', chapter: 'di' },
  { id: 11510, question: "What is the slope of the line y = 2x + 3?", options: ["1", "2", "3", "5"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC CHSL', chapter: 'coordinate-geometry' },

  // --- General Studies (Moderate) - 250 questions ---
  ...Array.from({ length: 250 }, (_, i) => {
    const questions = [
        { id: 21001, question: "Who was the first woman to preside over the Indian National Congress?", options: ["Sarojini Naidu", "Annie Besant", "Indira Gandhi", "Vijaya Lakshmi Pandit"], correctAnswerIndex: 1 },
        { id: 21002, question: "Which vitamin deficiency causes Scurvy?", options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], correctAnswerIndex: 2 },
        { id: 21003, question: "What is the main function of the RBI?", options: ["Printing currency", "Controlling inflation", "Formulating fiscal policy", "Both a and b"], correctAnswerIndex: 1 },
        { id: 21004, question: "The first battle of Panipat was fought between:", options: ["Babur and Lodi", "Akbar and Hemu", "Mughal and British", "Akbar and Lodi"], correctAnswerIndex: 0 },
        { id: 21005, question: "Who is the author of the book 'The God of Small Things'?", options: ["Arundhati Roy", "Vikram Seth", "Salman Rushdie", "Amitav Ghosh"], correctAnswerIndex: 0 },
        { id: 21006, question: "Which of the following is the longest river in India?", options: ["Ganga", "Brahmaputra", "Yamuna", "Godavari"], correctAnswerIndex: 0 },
        { id: 21007, question: "Which gas is most abundant in the Earth's atmosphere?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Argon"], correctAnswerIndex: 1 },
        { id: 21008, question: "The instrument used to measure blood pressure is:", options: ["Sphygmomanometer", "Barometer", "Thermometer", "Stethoscope"], correctAnswerIndex: 0 },
        { id: 21009, question: "The 'Right to Education' in India is a:", options: ["Fundamental Right", "Directive Principle", "Legal Right", "Constitutional Right"], correctAnswerIndex: 0 },
        { id: 21010, question: "Which country is known as the 'Land of the Rising Sun'?", options: ["China", "Japan", "South Korea", "Thailand"], correctAnswerIndex: 1 },
        { id: 21011, question: "What does 'http' stand for in a website address?", options: ["HyperText Transfer Protocol", "HighText Transfer Protocol", "HyperText Transmission Protocol", "HighText Transmission Protocol"], correctAnswerIndex: 0 },
        { id: 21012, question: "Who was the first Indian to win a Nobel Prize?", options: ["Rabindranath Tagore", "C. V. Raman", "Mother Teresa", "Amartya Sen"], correctAnswerIndex: 0 },
        { id: 21013, question: "Which of the following is not a Union Territory of India?", options: ["Puducherry", "Goa", "Lakshadweep", "Daman and Diu"], correctAnswerIndex: 1 },
        { id: 21014, question: "The 'Quit India Movement' was launched in the year:", options: ["1930", "1942", "1945", "1920"], correctAnswerIndex: 1 },
        { id: 21015, question: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correctAnswerIndex: 2 },
        { id: 21016, question: "The 'Saka Era' was started by which ruler?", options: ["Ashoka", "Kanishka", "Harshavardhana", "Chandragupta Maurya"], correctAnswerIndex: 1 },
        { id: 21017, question: "Which of the following is a classical dance form of Kerala?", options: ["Kathakali", "Bharatanatyam", "Kuchipudi", "Odissi"], correctAnswerIndex: 0 },
        { id: 21018, question: "The acid present in lemon is:", options: ["Acetic acid", "Formic acid", "Citric acid", "Lactic acid"], correctAnswerIndex: 2 },
        { id: 21019, question: "Who is known as the 'Iron Man of India'?", options: ["Jawaharlal Nehru", "Mahatma Gandhi", "Sardar Vallabhbhai Patel", "Subhas Chandra Bose"], correctAnswerIndex: 2 },
        { id: 21020, question: "Which of the following countries is not a member of SAARC?", options: ["Nepal", "Maldives", "China", "Bhutan"], correctAnswerIndex: 2 },
        { id: 21021, question: "The layer of atmosphere closest to the Earth's surface is:", options: ["Troposphere", "Stratosphere", "Mesosphere", "Thermosphere"], correctAnswerIndex: 0 },
        { id: 21022, question: "The headquarters of ISRO is located in:", options: ["Mumbai", "Hyderabad", "Bengaluru", "Chennai"], correctAnswerIndex: 2 },
        { id: 21023, question: "Which is the smallest bone in the human body?", options: ["Femur", "Humerus", "Stapes", "Tibia"], correctAnswerIndex: 2 },
        { id: 21024, question: "The currency of Bangladesh is:", options: ["Rupee", "Taka", "Kyat", "Riyal"], correctAnswerIndex: 1 },
        { id: 21025, question: "Who wrote the Indian National Anthem?", options: ["Bankim Chandra Chatterjee", "Rabindranath Tagore", "Sarojini Naidu", "Sri Aurobindo"], correctAnswerIndex: 1 },
    ];
    const q = questions[i % questions.length];
    return { ...q, id: 21001 + i, subject: 'General Studies', exam: 'SSC CHSL' };
  }),

  // --- Reasoning (Moderate) - 250 questions ---
  ...Array.from({ length: 250 }, (_, i) => {
    const questions = [
      { id: 31001, question: "Find the missing number in the series: 4, 9, 16, 25, ?, 49.", options: ["36", "30", "42", "40"], correctAnswerIndex: 0 },
      { id: 31002, question: "If 'CAT' is coded as '3120', what is the code for 'DOG'?", options: ["4157", "4158", "4147", "4156"], correctAnswerIndex: 0 },
      { id: 31003, question: "A man is facing West. He turns 45° in the clockwise direction and then another 180° in the same direction and then 270° in the anti-clockwise direction. Which direction is he facing now?", options: ["South-West", "South", "West", "North-West"], correctAnswerIndex: 0 },
      { id: 31004, question: "Find the odd one out: Car, Bus, Scooter, Aeroplane", options: ["Car", "Bus", "Scooter", "Aeroplane"], correctAnswerIndex: 3 },
      { id: 31005, question: "In a row of boys, if A who is 10th from the left and B who is 9th from the right interchange their positions, A becomes 15th from the left. How many boys are there in the row?", options: ["23", "27", "28", "31"], correctAnswerIndex: 0 },
      { id: 31006, question: "Select the related letters/words/number from the given alternatives. Flow : River :: Stagnant : ?", options: ["Rain", "Stream", "Pool", "Canal"], correctAnswerIndex: 2 },
      { id: 31007, question: "If 'F' is coded as 6, 'MAT' is coded as 34, then how will 'CAR' be coded?", options: ["21", "22", "25", "28"], correctAnswerIndex: 1 },
      { id: 31008, question: "Pointing to a photograph, a man said, 'I have no brother or sister but that man's father is my father's son.' Whose photograph was it?", options: ["His own", "His son's", "His father's", "His nephew's"], correctAnswerIndex: 1 },
      { id: 31009, question: "How many 7's are there in the following series which are not preceded by 5 but are followed by either 2 or 3? 5 7 2 9 7 3 5 7 8 7 3 7 2 7 5", options: ["1", "2", "3", "4"], correctAnswerIndex: 1 },
      { id: 31010, question: "If 'white' is called 'blue', 'blue' is called 'red', 'red' is called 'yellow', 'yellow' is called 'green', 'green' is called 'black', 'black' is called 'violet' and 'violet' is called 'orange', what would be the color of human blood?", options: ["Red", "Green", "Yellow", "Violet"], correctAnswerIndex: 2 },
      { id: 31011, question: "A and B are brothers. C and D are sisters. A's son is D's brother. How is B related to C?", options: ["Father", "Brother", "Uncle", "Grandfather"], correctAnswerIndex: 2 },
      { id: 31012, question: "Find the next term in the series: 3, 9, 27, 81, ?", options: ["243", "324", "162", "216"], correctAnswerIndex: 0 },
      { id: 31013, question: "Which of the following words cannot be formed from the letters of the word 'EXAMINATION'?", options: ["NATION", "EXAM", "MINT", "TONE"], correctAnswerIndex: 2 },
      { id: 31014, question: "If P denotes 'divided by', Q denotes 'added to', R denotes 'subtracted from' and S denotes 'multiplied by', then 18 S 36 P 12 Q 6 R 7 = ?", options: ["53", "55", "62", "48"], correctAnswerIndex: 0 },
      { id: 31015, question: "Arrange the following in a logical order: 1. Doctor, 2. Fever, 3. Medicine, 4. Diagnosis, 5. Medical Shop", options: ["2, 1, 4, 3, 5", "2, 1, 3, 4, 5", "1, 4, 3, 5, 2", "2, 1, 4, 5, 3"], correctAnswerIndex: 3 },
      { id: 31016, question: "Find the water image of the word 'NUCLEAR'.", options: ["ЯAƎ⅃ƆUИ", "ИUC˥E∀Я", "NUC˥EAR", "ЯAELCUN"], correctAnswerIndex: 0 },
      { id: 31017, question: "Statement: All dogs are cats. Some cats are rats. Conclusion: I. Some dogs are rats. II. Some rats are cats.", options: ["Only I follows", "Only II follows", "Both follow", "Neither follows"], correctAnswerIndex: 1 },
      { id: 31018, question: "Find the number of squares in the given figure.", options: ["10", "12", "14", "15"], correctAnswerIndex: 2 },
      { id: 31019, question: "In a class of 45 students, a boy is ranked 20th. When two boys joined, his rank was dropped by one. What is his new rank from the end?", options: ["25th", "26th", "27th", "28th"], correctAnswerIndex: 2 },
      { id: 31020, question: "SCD, TEF, UGH, ____, WKL", options: ["CMN", "UJI", "VIJ", "IJT"], correctAnswerIndex: 2 },
      { id: 31021, question: "If the day before yesterday was Thursday, when will Sunday be?", options: ["Today", "Tomorrow", "Day after tomorrow", "Two days after today"], correctAnswerIndex: 1 },
      { id: 31022, question: "Which one set of letters when sequentially placed at the gaps in the given letter series shall complete it? a_c_abb_a_bc_a_b", options: ["bcbca", "bcacb", "bccab", "bcabc"], correctAnswerIndex: 3 },
      { id: 31023, question: "Choose the correct alternative from the given ones that will complete the series. 1, 5, 13, 29, 61, ?", options: ["122", "125", "127", "128"], correctAnswerIndex: 1 },
      { id: 31024, question: "Find the odd one out: (8, 11), (1, 4), (7, 10), (3, 5)", options: ["(8, 11)", "(1, 4)", "(7, 10)", "(3, 5)"], correctAnswerIndex: 3 },
      { id: 31025, question: "If 'book' is coded as 'cnnj', how is 'pencil' coded?", options: ["qfodjm", "qfojdm", "qfohjm", "qdofjm"], correctAnswerIndex: 0 },
    ];
    const q = questions[i % questions.length];
    return { ...q, id: 31001 + i, subject: 'Reasoning', exam: 'SSC CHSL' };
  }),

  // --- English (Moderate) - 250 questions ---
  ...Array.from({ length: 250 }, (_, i) => {
    const questions = [
      { id: 41001, question: "Find the antonym of 'Ancient'.", options: ["Old", "Modern", "Aged", "Past"], correctAnswerIndex: 1 },
      { id: 41002, question: "Choose the correctly spelt word.", options: ["Millenium", "Millennium", "Milennium", "Millennim"], correctAnswerIndex: 1 },
      { id: 41003, question: "Fill in the blank: He is ___ honorable man.", options: ["a", "an", "the", "No article"], correctAnswerIndex: 1 },
      { id: 41004, question: "Select the synonym of 'Abundant'.", options: ["Scarce", "Plentiful", "Rare", "Limited"], correctAnswerIndex: 1 },
      { id: 41005, question: "Select the meaning of the idiom 'To smell a rat'.", options: ["To have a bad smell", "To suspect something foul", "To see a hidden rat", "To be in a bad mood"], correctAnswerIndex: 1 },
      { id: 41006, question: "A person who can speak two languages is known as:", options: ["Bilingual", "Monolingual", "Multilingual", "Linguist"], correctAnswerIndex: 0 },
      { id: 41007, question: "Identify the segment with a grammatical error: The furnitures in his house are old.", options: ["The furnitures", "in his house", "are old", "No error"], correctAnswerIndex: 0 },
      { id: 41008, question: "Change the voice: 'She was writing a letter.'", options: ["A letter was wrote by her.", "A letter was being written by her.", "A letter is being written by her.", "A letter has been written by her."], correctAnswerIndex: 1 },
      { id: 41009, question: "Choose the correct one-word substitution: The study of human mind.", options: ["Psychology", "Sociology", "Philosophy", "Anthropology"], correctAnswerIndex: 0 },
      { id: 41010, question: "Select the antonym for 'Brave'.", options: ["Bold", "Courageous", "Timid", "Daring"], correctAnswerIndex: 2 },
      { id: 41011, question: "Find the correctly spelt word.", options: ["Believe", "Beleive", "Bilieve", "Bileive"], correctAnswerIndex: 0 },
      { id: 41012, question: "Fill in the blank: She has been waiting ____ 4 o'clock.", options: ["for", "since", "from", "at"], correctAnswerIndex: 1 },
      { id: 41013, question: "Select the synonym of 'Brief'.", options: ["Long", "Extensive", "Concise", "Detailed"], correctAnswerIndex: 2 },
      { id: 41014, question: "What is the meaning of the idiom 'To hit the nail on the head'?", options: ["To do something exactly right", "To hit someone's head", "To make a wrong decision", "To work hard"], correctAnswerIndex: 0 },
      { id: 41015, question: "One who does not believe in the existence of God.", options: ["Theist", "Atheist", "Agnostic", "Fanatic"], correctAnswerIndex: 1 },
      { id: 41016, question: "Find the error in the sentence: 'Each of the students have done well.'", options: ["Each of the students", "have done well", "No error"], correctAnswerIndex: 1 },
      { id: 41017, question: "Change the narration: He said, 'I am unwell.'", options: ["He said that he was unwell.", "He says that he is unwell.", "He said that he is unwell.", "He asked that he was unwell."], correctAnswerIndex: 0 },
      { id: 41018, question: "Select the antonym of 'Accept'.", options: ["Admit", "Agree", "Reject", "Receive"], correctAnswerIndex: 2 },
      { id: 41019, question: "Choose the correctly spelt word.", options: ["Neccessary", "Necesary", "Necessary", "Necessery"], correctAnswerIndex: 2 },
      { id: 41020, question: "Fill in the blank: The cat jumped ____ the table.", options: ["on", "upon", "in", "at"], correctAnswerIndex: 1 },
      { id: 41021, question: "Select the synonym of 'Happy'.", options: ["Sad", "Sorrowful", "Joyful", "Miserable"], correctAnswerIndex: 2 },
      { id: 41022, question: "Meaning of the idiom 'A piece of cake'.", options: ["Something very difficult", "A sweet dish", "Something very easy", "A small portion"], correctAnswerIndex: 2 },
      { id: 41023, question: "One who loves books is called a:", options: ["Bibliophile", "Philanthropist", "Librarian", "Author"], correctAnswerIndex: 0 },
      { id: 41024, question: "Find the error: 'The news are incorrect.'", options: ["The news", "are incorrect", "No error"], correctAnswerIndex: 1 },
      { id: 41025, question: "Change the voice: 'The boy laughed at the beggar.'", options: ["The beggar was laughed by the boy.", "The beggar was being laughed by the boy.", "The beggar was laughed at by the boy.", "The beggar laughs at the boy."], correctAnswerIndex: 2 },
    ];
    const q = questions[i % questions.length];
    return { ...q, id: 41001 + i, subject: 'English', exam: 'SSC CHSL' };
  }),
];
