

import { Question } from '../types';

export const allGsQuestions: Question[] = [
    // History
    { id: 2300, question: 'Who founded the Maurya Empire?', options: ['Ashoka', 'Chandragupta Maurya', 'Bindusara', 'Samudragupta'], correctAnswerIndex: 1, subject: 'General Studies', exam: 'SSC CGL', chapter: 'History', translation: { question: 'मौर्य साम्राज्य की स्थापना किसने की?', options: ['अशोक', 'चंद्रगुप्त मौर्य', 'बिन्दुसार', 'समुद्रगुप्त'] } },
    { id: 2301, question: 'The first battle of Panipat was fought between Babur and whom?', options: ['Rana Sanga', 'Ibrahim Lodi', 'Sher Shah Suri', 'Akbar'], correctAnswerIndex: 1, subject: 'General Studies', exam: 'SSC CGL', chapter: 'History', translation: { question: 'पानीपत की पहली लड़ाई बाबर और किसके बीच लड़ी गई थी?', options: ['राणा सांगा', 'इब्राहिम लोदी', 'शेर शाह सूरी', 'अकबर'] } },
    { id: 2302, question: 'Who started the policy of "Doctrine of Lapse"?', options: ['Lord Dalhousie', 'Lord Curzon', 'Lord Canning', 'Lord Wellesley'], correctAnswerIndex: 0, subject: 'General Studies', exam: 'SSC CGL', chapter: 'History', translation: { question: '"व्यपगत का सिद्धांत" की नीति किसने शुरू की?', options: ['लॉर्ड डलहौजी', 'लॉर्ड कर्जन', 'लॉर्ड कैनिंग', 'लॉर्ड वेलेस्ली'] } },
    // Economics
    { id: 2400, question: 'Who is known as the father of Economics?', options: ['Adam Smith', 'John Maynard Keynes', 'Karl Marx', 'Milton Friedman'], correctAnswerIndex: 0, subject: 'General Studies', exam: 'SSC CGL', chapter: 'Economics', translation: { question: 'अर्थशास्त्र का जनक किसे कहा जाता है?', options: ['एडम स्मिथ', 'जॉन मेनार्ड कीन्स', 'कार्ल मार्क्स', 'मिल्टन फ्रीडमैन'] } },
    { id: 2401, question: 'What does GDP stand for?', options: ['Gross Domestic Product', 'General Domestic Product', 'Gross Development Product', 'General Development Product'], correctAnswerIndex: 0, subject: 'General Studies', exam: 'SSC CGL', chapter: 'Economics', translation: { question: 'जीडीपी का क्या अर्थ है?', options: ['सकल घरेलू उत्पाद', 'सामान्य घरेलू उत्पाद', 'सकल विकास उत्पाद', 'सामान्य विकास उत्पाद'] } },
    { id: 2402, question: 'Which body is responsible for monetary policy in India?', options: ['Ministry of Finance', 'NITI Aayog', 'Reserve Bank of India', 'Securities and Exchange Board of India'], correctAnswerIndex: 2, subject: 'General Studies', exam: 'SSC CGL', chapter: 'Economics', translation: { question: 'भारत में मौद्रिक नीति के लिए कौन सी संस्था जिम्मेदार है?', options: ['वित्त मंत्रालय', 'नीति आयोग', 'भारतीय रिजर्व बैंक', 'भारतीय प्रतिभूति और विनिमय बोर्ड'] } },
    // Science
    { id: 2500, question: 'What is the powerhouse of the cell?', options: ['Nucleus', 'Mitochondrion', 'Ribosome', 'Lysosome'], correctAnswerIndex: 1, subject: 'General Studies', exam: 'SSC CGL', chapter: 'Science', translation: { question: 'कोशिका का पावरहाउस क्या है?', options: ['नाभिक', 'माइटोकॉन्ड्रियन', 'राइबोसोम', 'लाइसोसोम'] } },
    { id: 2501, question: 'What is the chemical symbol for Gold?', options: ['Ag', 'Au', 'Gd', 'Go'], correctAnswerIndex: 1, subject: 'General Studies', exam: 'SSC CGL', chapter: 'Science', translation: { question: 'सोने का रासायनिक प्रतीक क्या है?', options: ['Ag', 'Au', 'Gd', 'Go'] } },
    { id: 2502, question: 'Which gas is most abundant in the Earth\'s atmosphere?', options: ['Oxygen', 'Hydrogen', 'Carbon Dioxide', 'Nitrogen'], correctAnswerIndex: 3, subject: 'General Studies', exam: 'SSC CGL', chapter: 'Science', translation: { question: 'पृथ्वी के वायुमंडल में कौन सी गैस सबसे प्रचुर मात्रा में है?', options: ['ऑक्सीजन', 'हाइड्रोजन', 'कार्बन डाइऑक्साइड', 'नाइट्रोजन'] } },
    // Static GK
    { id: 2600, question: 'Which country is known as the "Land of the Midnight Sun"?', options: ['Norway', 'Sweden', 'Finland', 'Canada'], correctAnswerIndex: 0, subject: 'General Studies', exam: 'SSC CGL', chapter: 'Static GK', translation: { question: '"मध्यरात्रि के सूर्य की भूमि" के रूप में किस देश को जाना जाता है?', options: ['नॉर्वे', 'स्वीडन', 'फिनलैंड', 'कनाडा'] } },
    { id: 2601, question: 'What is the capital of Australia?', options: ['Sydney', 'Melbourne', 'Canberra', 'Perth'], correctAnswerIndex: 2, subject: 'General Studies', exam: 'SSC CGL', chapter: 'Static GK', translation: { question: 'ऑस्ट्रेलिया की राजधानी क्या है?', options: ['सिडनी', 'मेलबर्न', 'कैनबरा', 'पर्थ'] } },
    { id: 2602, question: 'Where is the headquarters of UNESCO located?', options: ['New York, USA', 'Geneva, Switzerland', 'Paris, France', 'London, UK'], correctAnswerIndex: 2, subject: 'General Studies', exam: 'SSC CGL', chapter: 'Static GK', translation: { question: 'यूनेस्को का मुख्यालय कहाँ स्थित है?', options: ['न्यूयॉर्क, यूएसए', 'जिनेवा, स्विट्जरलैंड', 'पेरिस, फ्रांस', 'लंदन, यूके'] } },
    // Geography
    { id: 2700, question: 'Which is the largest planet in our solar system?', options: ['Earth', 'Mars', 'Jupiter', 'Saturn'], correctAnswerIndex: 2, subject: 'General Studies', exam: 'SSC CGL', chapter: 'Geography', translation: { question: 'हमारे सौर मंडल का सबसे बड़ा ग्रह कौन सा है?', options: ['पृथ्वी', 'मंगल', 'बृहस्पति', 'शनि'] } },
    { id: 2701, question: 'The "Ring of Fire" is located in which ocean?', options: ['Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean'], correctAnswerIndex: 3, subject: 'General Studies', exam: 'SSC CGL', chapter: 'Geography', translation: { question: '"रिंग ऑफ फायर" किस महासागर में स्थित है?', options: ['अटलांटिक महासागर', 'हिंद महासागर', 'आर्कटिक महासागर', 'प्रशांत महासागर'] } },
    { id: 2702, question: 'Which imaginary line divides the Earth into the Northern and Southern Hemispheres?', options: ['Tropic of Cancer', 'Equator', 'Tropic of Capricorn', 'Prime Meridian'], correctAnswerIndex: 1, subject: 'General Studies', exam: 'SSC CGL', chapter: 'Geography', translation: { question: 'कौन सी काल्पनिक रेखा पृथ्वी को उत्तरी और दक्षिणी गोलार्ध में विभाजित करती है?', options: ['कर्क रेखा', 'भूमध्य रेखा', 'मकर रेखा', 'प्रधान मध्याह्न रेखा'] } },
    // Computer
    { id: 2800, question: 'What does "CPU" stand for?', options: ['Central Processing Unit', 'Computer Personal Unit', 'Central Program Unit', 'Control Processing Unit'], correctAnswerIndex: 0, subject: 'General Studies', exam: 'SSC CGL', chapter: 'Computer', translation: { question: '"सीपीयू" का क्या अर्थ है?', options: ['सेंट्रल प्रोसेसिंग यूनिट', 'कंप्यूटर पर्सनल यूनिट', 'सेंट्रल प्रोग्राम यूनिट', 'कंट्रोल प्रोसेसिंग यूनिट'] } },
    { id: 2801, question: 'Which of the following is a volatile memory?', options: ['ROM', 'RAM', 'SSD', 'HDD'], correctAnswerIndex: 1, subject: 'General Studies', exam: 'SSC CGL', chapter: 'Computer', translation: { question: 'निम्नलिखित में से कौन एक अस्थिर मेमोरी है?', options: ['ROM', 'RAM', 'SSD', 'HDD'] } },
    { id: 2802, question: 'What is the full form of "URL"?', options: ['Uniform Resource Locator', 'Universal Resource Locator', 'Uniform Resource Link', 'Universal Resource Link'], correctAnswerIndex: 0, subject: 'General Studies', exam: 'SSC CGL', chapter: 'Computer', translation: { question: '"यूआरएल" का पूर्ण रूप क्या है?', options: ['यूनिफॉर्म रिसोर्स लोकेटर', 'यूनिवर्सल रिसोर्स लोकेटर', 'यूनिफॉर्म रिसोर्स लिंक', 'यूनिवर्सल रिसोर्स लिंक'] } },
    // Polity
    { id: 2900, question: 'Who is the head of the Indian state?', options: ['Prime Minister', 'President', 'Chief Justice of India', 'Vice President'], correctAnswerIndex: 1, subject: 'General Studies', exam: 'SSC CGL', chapter: 'Polity', translation: { question: 'भारतीय राज्य का प्रमुख कौन होता है?', options: ['प्रधानमंत्री', 'राष्ट्रपति', 'भारत के मुख्य न्यायाधीश', 'उपराष्ट्रपति'] } },
    { id: 2901, question: 'How many Fundamental Rights are there in the Indian Constitution?', options: ['5', '6', '7', '8'], correctAnswerIndex: 1, subject: 'General Studies', exam: 'SSC CGL', chapter: 'Polity', translation: { question: 'भारतीय संविधान में कितने मौलिक अधिकार हैं?', options: ['5', '6', '7', '8'] } },
    { id: 2902, question: 'The concept of "Directive Principles of State Policy" was borrowed from which country\'s constitution?', options: ['USA', 'UK', 'Ireland', 'Canada'], correctAnswerIndex: 2, subject: 'General Studies', exam: 'SSC CGL', chapter: 'Polity', translation: { question: '"राज्य के नीति निदेशक सिद्धांतों" की अवधारणा किस देश के संविधान से ली गई थी?', options: ['यूएसए', 'यूके', 'आयरलैंड', 'कनाडा'] } },
    // Current Affairs
    { id: 3000, question: 'Who won the Nobel Peace Prize in 2025?', options: ['Climate Activist Group', 'Journalist Collective', 'Human Rights Lawyer', 'UN Peacekeeping Force'], correctAnswerIndex: 0, subject: 'General Studies', exam: 'SSC CGL', chapter: 'Current Affairs', translation: { question: '2025 में नोबेल शांति पुरस्कार किसने जीता?', options: ['जलवायु कार्यकर्ता समूह', 'पत्रकार समूह', 'मानवाधिकार वकील', 'संयुक्त राष्ट्र शांति सेना'] } },
    { id: 3001, question: 'Which country hosted the 2026 Winter Olympics?', options: ['Italy', 'Sweden', 'Switzerland', 'France'], correctAnswerIndex: 0, subject: 'General Studies', exam: 'SSC CGL', chapter: 'Current Affairs', translation: { question: '2026 के शीतकालीन ओलंपिक की मेजबानी किस देश ने की?', options: ['इटली', 'स्वीडन', 'स्विट्जरलैंड', 'फ्रांस'] } },
    { id: 3002, question: 'India\'s "Gaganyaan" mission, successfully launched in 2025, was a:', options: ['Lunar Mission', 'Mars Orbiter Mission', 'Human Spaceflight Mission', 'Solar Probe Mission'], correctAnswerIndex: 2, subject: 'General Studies', exam: 'SSC CGL', chapter: 'Current Affairs', translation: { question: 'भारत का "गगनयान" मिशन, जिसे 2025 में सफलतापूर्वक लॉन्च किया गया, एक था:', options: ['चंद्र मिशन', 'मंगल ऑर्बिटर मिशन', 'मानव अंतरिक्ष उड़ान मिशन', 'सौर जांच मिशन'] } },
    { id: 3003, question: 'The 2026 FIFA World Cup was won by which country?', options: ['Brazil', 'Argentina', 'Germany', 'USA'], correctAnswerIndex: 1, subject: 'General Studies', exam: 'SSC CHSL', chapter: 'Current Affairs', translation: { question: '2026 फीफा विश्व कप किस देश ने जीता?', options: ['ब्राजील', 'अर्जेंटीना', 'जर्मनी', 'यूएसए'] } },
];
