import { Question } from '../types';

export const mtsQuestions: Question[] = [
  // --- Maths (Easy/Moderate) ---
  // Number System (10)
  { id: 12001, question: "What is the sum of the first 10 even numbers?", options: ["110", "120", "100", "90"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'number-system' },
  { id: 12002, question: "Which is the smallest prime number?", options: ["0", "1", "2", "3"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'number-system' },
  { id: 12003, question: "What is the place value of 5 in 15,203?", options: ["5", "50", "500", "5000"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC MTS', chapter: 'number-system' },
  { id: 12004, question: "The product of two numbers is 120 and their HCF is 2. What is their LCM?", options: ["60", "120", "240", "30"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'number-system' },
  { id: 12005, question: "Simplify: 12 + 15 ÷ 3 × 2", options: ["18", "22", "27", "9"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'number-system' },
  { id: 12006, question: "How many numbers between 1 and 100 are divisible by 7?", options: ["12", "13", "14", "15"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'number-system' },
  { id: 12007, question: "The sum of the digits of a two-digit number is 8. The number obtained by reversing the digits is 18 more than the original number. Find the number.", options: ["26", "35", "53", "62"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'number-system' },
  { id: 12008, question: "What is 1004 × 996?", options: ["999984", "99984", "99840", "999994"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'number-system' },
  { id: 12009, question: "Find the unit digit of 7^105.", options: ["1", "3", "5", "7"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC MTS', chapter: 'number-system' },
  { id: 12010, question: "The predecessor of -99 is:", options: ["-98", "-100", "98", "100"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'number-system' },

  // Percentages (10)
  { id: 12011, question: "What is 50% of 200?", options: ["50", "100", "150", "200"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'percentages' },
  { id: 12012, question: "A shopkeeper bought a chair for Rs. 500 and sold it for Rs. 550. What is his profit percentage?", options: ["10%", "5%", "15%", "12%"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'percentages' },
  { id: 12013, question: "Convert 3/5 into percentage.", options: ["30%", "40%", "50%", "60%"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC MTS', chapter: 'percentages' },
  { id: 12014, question: "If 20% of a number is 80, what is the number?", options: ["160", "200", "400", "800"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'percentages' },
  { id: 12015, question: "An item marked at Rs. 840 is sold for Rs. 714. What is the discount %?", options: ["10%", "15%", "20%", "25%"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'percentages' },
  { id: 12016, question: "In a school of 1200 students, 70% are boys. Find the number of girls.", options: ["360", "840", "400", "300"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'percentages' },
  { id: 12017, question: "A number is first increased by 10% and then decreased by 10%. The number:", options: ["Remains the same", "Decreases by 1%", "Increases by 1%", "Decreases by 2%"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'percentages' },
  { id: 12018, question: "Ram's salary is Rs. 10,000. He gets a raise of 10%. What is his new salary?", options: ["Rs. 11,000", "Rs. 10,100", "Rs. 9,000", "Rs. 10,500"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'percentages' },
  { id: 12019, question: "What is 0.05 as a percentage?", options: ["50%", "5%", "0.5%", "0.05%"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'percentages' },
  { id: 12020, question: "Out of 40 students in a class, 8 are absent. What percentage of students are present?", options: ["80%", "20%", "90%", "75%"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'percentages' },
  
  // Ratio and Proportion (10)
  { id: 12021, question: "If a:b = 2:3 and b:c = 4:5, what is a:c?", options: ["2:5", "8:15", "3:5", "4:3"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'ratio-proportion' },
  { id: 12022, question: "Divide Rs. 60 in the ratio 1:2 between A and B.", options: ["A=20, B=40", "A=30, B=30", "A=40, B=20", "A=10, B=50"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'ratio-proportion' },
  { id: 12023, question: "The ratio of boys to girls in a school is 4:5. If there are 200 boys, find the number of girls.", options: ["250", "200", "300", "160"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'ratio-proportion' },
  { id: 12024, question: "Find the fourth proportional to 3, 7, 9.", options: ["21", "13", "27", "19"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'ratio-proportion' },
  { id: 12025, question: "If 2A = 3B = 4C, then A:B:C is:", options: ["2:3:4", "4:3:2", "6:4:3", "3:4:6"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'ratio-proportion' },
  { id: 12026, question: "Two numbers are in the ratio of 3:5. If the sum of numbers is 80, find the numbers.", options: ["30, 50", "20, 60", "10, 70", "40, 40"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'ratio-proportion' },
  { id: 12027, question: "Find the mean proportional between 4 and 25.", options: ["10", "12", "14.5", "100"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'ratio-proportion' },
  { id: 12028, question: "A bag contains 1 rupee, 50 paise and 25 paise coins in the ratio 5:6:7. If the total amount is Rs. 390, find the number of 25 paise coins.", options: ["280", "240", "200", "260"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'ratio-proportion' },
  { id: 12029, question: "If x/5 = y/8, then (x+5):(y+8) is equal to:", options: ["3:5", "13:8", "8:5", "5:8"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC MTS', chapter: 'ratio-proportion' },
  { id: 12030, question: "The ratio of two numbers is 3:4. If 5 is subtracted from each, the ratio becomes 5:7. Find the numbers.", options: ["30, 40", "15, 20", "18, 24", "12, 16"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'ratio-proportion' },

  // Averages (10)
  { id: 12031, question: "Find the average of 10, 20, 30, 40, 50.", options: ["25", "30", "35", "40"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'averages' },
  { id: 12032, question: "The average of 3 numbers is 15. If two numbers are 10 and 20, find the third number.", options: ["15", "10", "25", "5"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'averages' },
  { id: 12033, question: "The average age of 5 boys is 12 years. If a new boy joins, the average becomes 13 years. What is the age of the new boy?", options: ["18 years", "15 years", "12 years", "20 years"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'averages' },
  { id: 12034, question: "Find the average of the first five multiples of 3.", options: ["3", "6", "9", "12"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'averages' },
  { id: 12035, question: "A cricketer scored 50, 60, 55, 65, and 70 in five matches. What is his average score?", options: ["60", "61", "62", "59"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'averages' },
  { id: 12036, question: "The average of 5 consecutive even numbers is 12. Find the smallest number.", options: ["8", "10", "6", "14"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'averages' },
  { id: 12037, question: "The average weight of 10 students is 40 kg. If a student of 51 kg leaves, what is the new average?", options: ["39 kg", "40 kg", "41 kg", "38 kg"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'averages' },
  { id: 12038, question: "The average of x, y, and z is 20. If x=10 and y=20, find z.", options: ["20", "30", "40", "10"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'averages' },
  { id: 12039, question: "The average monthly salary of 12 workers is Rs. 1500. If the manager's salary is added, the average salary becomes Rs. 1600. What is the manager's salary?", options: ["Rs. 2800", "Rs. 2900", "Rs. 2700", "Rs. 3000"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'averages' },
  { id: 12040, question: "Find the average of all prime numbers between 20 and 40.", options: ["30", "29.5", "29", "28.5"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'averages' },

  // Simple and Compound Interest (10)
  { id: 12041, question: "What is the simple interest on Rs. 1000 for 2 years at 5% per annum?", options: ["Rs. 100", "Rs. 200", "Rs. 50", "Rs. 150"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'si-ci' },
  { id: 12042, question: "At what rate of simple interest will Rs. 500 amount to Rs. 600 in 4 years?", options: ["5%", "4%", "6%", "10%"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'si-ci' },
  { id: 12043, question: "Find the compound interest on Rs. 1000 for 2 years at 10% per annum.", options: ["Rs. 200", "Rs. 210", "Rs. 100", "Rs. 220"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'si-ci' },
  { id: 12044, question: "In how many years will a sum of money double itself at 10% simple interest?", options: ["10 years", "8 years", "5 years", "20 years"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'si-ci' },
  { id: 12045, question: "The difference between SI and CI on a certain sum for 2 years at 5% is Rs. 10. Find the sum.", options: ["Rs. 4000", "Rs. 2000", "Rs. 5000", "Rs. 3000"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'si-ci' },
  { id: 12046, question: "A sum of money amounts to Rs. 9680 in 2 years and to Rs. 10648 in 3 years at CI. Find the rate of interest.", options: ["10%", "12%", "5%", "8%"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'si-ci' },
  { id: 12047, question: "Find the simple interest on Rs. 2000 for 6 months at 4% per annum.", options: ["Rs. 40", "Rs. 80", "Rs. 20", "Rs. 60"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'si-ci' },
  { id: 12048, question: "A sum of Rs. 800 becomes Rs. 956 in 3 years at a certain rate of simple interest. If the rate of interest is increased by 4%, what amount will Rs. 800 become in 3 years?", options: ["Rs. 1020.80", "Rs. 1052", "Rs. 980", "Rs. 1000"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'si-ci' },
  { id: 12049, question: "Find compound interest on Rs. 8000 at 15% per annum for 2 years and 4 months, compounded annually.", options: ["Rs. 3109", "Rs. 3091", "Rs. 2980", "Rs. 3000"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'si-ci' },
  { id: 12050, question: "What will be the simple interest earned on an amount of Rs. 16,800 in 9 months at the rate of 6.25% p.a.?", options: ["Rs. 787.50", "Rs. 812.50", "Rs. 860", "Rs. 887.50"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'si-ci' },

  // Profit, Loss and Discount (10)
  { id: 12051, question: "A man buys a toy for Rs. 25 and sells it for Rs. 30. Find his gain percent.", options: ["20%", "25%", "15%", "10%"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'profit-loss-discount' },
  { id: 12052, question: "If CP of an article is Rs. 80 and SP is Rs. 100, what is the profit percent?", options: ["20%", "25%", "30%", "15%"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'profit-loss-discount' },
  { id: 12053, question: "An article is sold for Rs. 500, and there is a loss of 20%. At what price should it be sold to gain 10%?", options: ["Rs. 625", "Rs. 687.50", "Rs. 550", "Rs. 700"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'profit-loss-discount' },
  { id: 12054, question: "A shopkeeper offers a 10% discount on an item. If the marked price is Rs. 200, find the selling price.", options: ["Rs. 180", "Rs. 190", "Rs. 200", "Rs. 220"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'profit-loss-discount' },
  { id: 12055, question: "By selling a book for Rs. 115.20, a man loses 10%. At what price should he sell it to gain 5%?", options: ["Rs. 128", "Rs. 134.40", "Rs. 130", "Rs. 120"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'profit-loss-discount' },
  { id: 12056, question: "A dealer bought a bicycle for Rs. 1200 and spent Rs. 300 on repairs. He sold it for Rs. 1800. Find his profit percent.", options: ["20%", "25%", "30%", "15%"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'profit-loss-discount' },
  { id: 12057, question: "If the cost price of 12 pens is equal to the selling price of 8 pens, the gain percent is:", options: ["25%", "33 1/3%", "50%", "66 2/3%"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'profit-loss-discount' },
  { id: 12058, question: "A shopkeeper marks his goods 20% above cost price and allows a discount of 10%. Find his gain percent.", options: ["10%", "8%", "12%", "9%"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'profit-loss-discount' },
  { id: 12059, question: "Find a single discount equivalent to two successive discounts of 20% and 10%.", options: ["30%", "28%", "25%", "22%"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'profit-loss-discount' },
  { id: 12060, question: "A man sold a horse at a loss of 7%. Had he been able to sell it at a gain of 9%, it would have fetched Rs. 64 more. What was the cost price?", options: ["Rs. 400", "Rs. 350", "Rs. 450", "Rs. 500"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'profit-loss-discount' },

  // Mixtures and Allegations (10)
  { id: 12061, question: "In what ratio must rice at Rs. 9.30 per kg be mixed with rice at Rs. 10.80 per kg so that the mixture be worth Rs. 10 per kg?", options: ["8:7", "7:8", "6:5", "5:6"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'mixtures-allegations' },
  { id: 12062, question: "A mixture of 40 liters of milk and water contains 10% of water. How much water must be added to make the water 20% in the new mixture?", options: ["5 liters", "6 liters", "8 liters", "10 liters"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'mixtures-allegations' },
  { id: 12063, question: "How many kgs of salt at 42 paise per kg must a man mix with 25 kg of salt at 24 paise per kg so that he may, on selling the mixture at 40 paise per kg gain 25% on the outlay?", options: ["15 kg", "20 kg", "25 kg", "30 kg"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'mixtures-allegations' },
  { id: 12064, question: "A container contains 40 litres of milk. From this container 4 litres of milk was taken out and replaced by water. This process was repeated further two times. How much milk is now contained by the container?", options: ["26.34 litres", "27.36 litres", "28 litres", "29.16 litres"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC MTS', chapter: 'mixtures-allegations' },
  { id: 12065, question: "In what ratio must water be mixed with spirit to gain 12.5% by selling it at cost price?", options: ["1:8", "1:7", "1:9", "1:10"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'mixtures-allegations' },
  { id: 12066, question: "A milkman has two cans of milk containing 75% milk and 50% milk respectively. In what ratio should he mix these two to get a mixture of 60% milk?", options: ["1:2", "2:1", "2:3", "3:2"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'mixtures-allegations' },
  { id: 12067, question: "A mixture of 20 kg of spirit and water contains 10% water. How much water must be added to this mixture to raise the percentage of water to 25%?", options: ["4 kg", "5 kg", "8 kg", "30 kg"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'mixtures-allegations' },
  { id: 12068, question: "Two alloys are both made up of copper and tin. The ratio of copper and tin in the first alloy is 1 : 3 and in the second alloy is 2 : 5. In what ratio should the two alloys be mixed to obtain a new alloy in which the ratio of tin and copper be 8 : 3?", options: ["3:5", "4:7", "3:8", "5:11"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'mixtures-allegations' },
  { id: 12069, question: "A can contains a mixture of two liquids A and B in the ratio 7 : 5. When 9 litres of mixture are drawn off and the can is filled with B, the ratio of A and B becomes 7 : 9. How many litres of liquid A was contained by the can initially?", options: ["10", "20", "21", "25"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'mixtures-allegations' },
  { id: 12070, question: "A vessel has 60 litres of a solution of acid and water having 80% acid. How much water be added to make it a solution in which acid forms 60%?", options: ["12 litres", "20 litres", "24 litres", "30 litres"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'mixtures-allegations' },

  // Time and Work (10)
  { id: 12071, question: "A can do a work in 6 days and B in 9 days. How many days will both take together to complete the work?", options: ["3.6 days", "4 days", "5 days", "7.5 days"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'time-work' },
  { id: 12072, question: "A and B together can do a piece of work in 4 days. If A alone can do it in 6 days, in how many days B can alone do it?", options: ["8 days", "10 days", "12 days", "14 days"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'time-work' },
  { id: 12073, question: "A can lay railway track between two given stations in 16 days and B can do the same job in 12 days. With help of C, they did the job in 4 days only. Then, C alone can do the job in:", options: ["9 1/5 days", "9 2/5 days", "9 3/5 days", "10 days"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'time-work' },
  { id: 12074, question: "A, B and C can do a piece of work in 20, 30 and 60 days respectively. In how many days can A do the work if he is assisted by B and C on every third day?", options: ["12 days", "15 days", "16 days", "18 days"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'time-work' },
  { id: 12075, question: "A is twice as good as workman as B and together they finish a piece of work in 14 days. The number of days taken by A alone to finish the work is:", options: ["11", "21", "28", "42"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'time-work' },
  { id: 12076, question: "If 3 men or 6 women can do a piece of work in 16 days, in how many days can 12 men and 8 women do the same piece of work?", options: ["3 days", "4 days", "5 days", "6 days"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'time-work' },
  { id: 12077, question: "Pipe A can fill a tank in 5 hours, pipe B in 10 hours and pipe C in 30 hours. If all the pipes are open, in how many hours will the tank be filled?", options: ["2", "2.5", "3", "3.5"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'time-work' },
  { id: 12078, question: "A and B can do a work in 8 days, B and C can do the same work in 12 days. A, B and C together can finish it in 6 days. A and C together will do it in :", options: ["4 days", "6 days", "8 days", "12 days"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'time-work' },
  { id: 12079, question: "A can do a certain work in 12 days. B is 60% more efficient than A. How many days does B alone take to do the same job?", options: ["6", "7.5", "8", "8.5"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'time-work' },
  { id: 12080, question: "A and B can do a work in 12 days, B and C in 15 days, C and A in 20 days. If A, B and C work together, they will complete the work in:", options: ["5 days", "7 5/6 days", "10 days", "15 2/3 days"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'time-work' },

  // Time, Speed and Distance (10)
  { id: 12081, question: "A man walks at 5 km/hr and crosses a bridge in 15 minutes. The length of the bridge is:", options: ["1000 m", "1250 m", "1500 m", "1750 m"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'time-speed-distance' },
  { id: 12082, question: "A train 110 meters long is running with a speed of 60 kmph. In what time will it pass a man who is running at 6 kmph in the direction opposite to that in which the train is going?", options: ["5 sec", "6 sec", "7 sec", "10 sec"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'time-speed-distance' },
  { id: 12083, question: "The speed of a boat in still water is 15 km/hr and the rate of current is 3 km/hr. The distance travelled downstream in 12 minutes is:", options: ["3.6 km", "2.4 km", "1.8 km", "1.2 km"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'time-speed-distance' },
  { id: 12084, question: "A man on a tour travels first 160 km at 64 km/hr and the next 160 km at 80 km/hr. Find the average speed for the tour.", options: ["71.11 km/hr", "72 km/hr", "70 km/hr", "70.5 km/hr"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'time-speed-distance' },
  { id: 12085, question: "A cyclist covers a distance of 750 meter in 2 minutes 30 seconds. What is the speed in km/hr of the cyclist?", options: ["15 km/hr", "18 km/hr", "20 km/hr", "24 km/hr"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'time-speed-distance' },
  { id: 12086, question: "A train moves with a speed of 180 km/hr. Its speed in metres per second is:", options: ["5 m/s", "30 m/s", "40 m/s", "50 m/s"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC MTS', chapter: 'time-speed-distance' },
  { id: 12087, question: "If a student walks from his house to school at 5 km/hr, he is late by 30 minutes. However, if he walks at 6 km/hr, he is late by 5 minutes only. The distance of his school from his house is:", options: ["12.5 km", "15 km", "17.5 km", "20 km"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'time-speed-distance' },
  { id: 12088, question: "Two trains starting at the same time from two stations 200 km apart and going in opposite direction cross each other at a distance of 110 km from one of the stations. What is the ratio of their speeds?", options: ["11:9", "7:3", "11:20", "9:20"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'time-speed-distance' },
  { id: 12089, question: "A boat running downstream covers a distance of 16 km in 2 hours while for covering the same distance upstream, it takes 4 hours. What is the speed of the boat in still water?", options: ["4 km/hr", "6 km/hr", "8 km/hr", "Data inadequate"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'time-speed-distance' },
  { id: 12090, question: "A car can cover a certain distance in 4.5 hours. If the speed is increased by 5 km/hr, it would take 0.5 hour less to cover the same distance. Find the slower speed of the car.", options: ["40 km/hr", "45 km/hr", "50 km/hr", "60 km/hr"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'time-speed-distance' },

  // Partnership (10)
  { id: 12091, question: "A, B and C started a business by investing Rs. 1,20,000, Rs. 1,35,000 and Rs. 1,50,000 respectively. Find the share of C out of an annual profit of Rs. 56,700.", options: ["Rs. 16,800", "Rs. 18,900", "Rs. 21,000", "Rs. 23,100"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'partnership' },
  { id: 12092, question: "A starts business with Rs. 7000 and after 5 months, B joins as partner. After a year, the profit is divided in the ratio 2:3. What is B's contribution in the capital?", options: ["Rs. 10,000", "Rs. 12,000", "Rs. 15,000", "Rs. 18,000"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC MTS', chapter: 'partnership' },
  { id: 12093, question: "A and B invest in a business in the ratio 3 : 2. If 5% of the total profit goes to charity and A's share is Rs. 855, the total profit is:", options: ["Rs. 1425", "Rs. 1500", "Rs. 1537.50", "Rs. 1576"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'partnership' },
  { id: 12094, question: "P and Q invest Rs. 5000 and Rs. 8000 in a business. If the total profit at the end of the year is Rs. 2600, what is P's share?", options: ["Rs. 1000", "Rs. 1200", "Rs. 1600", "Rs. 800"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'partnership' },
  { id: 12095, question: "A and B start a business with Rs. 1500 and Rs. 2500. After 4 months, C joins them with Rs. 3000. If the profit at the end of the year is Rs. 5700, find C's share.", options: ["Rs. 1500", "Rs. 1800", "Rs. 2000", "Rs. 2400"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'partnership' },
  { id: 12096, question: "A, B and C enter into partnership. A invests Rs. 2560 and B invests Rs. 2000. At the end of the year, they gain Rs. 1105, out of which A gets Rs. 320. C's capital is:", options: ["Rs. 4280", "Rs. 4028", "Rs. 3840", "Rs. 4820"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'partnership' },
  { id: 12097, question: "Four milkmen rented a pasture. A grazed 24 cows for 3 months; B 10 cows for 5 months; C 35 cows for 4 months and D 21 cows for 3 months. If A's share of rent is Rs. 720, find the total rent of the pasture.", options: ["Rs. 3250", "Rs. 3350", "Rs. 3450", "Rs. 3550"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'partnership' },
  { id: 12098, question: "A and B started a partnership business investing some amount in the ratio of 3 : 5. C joined them after six months with an amount equal to that of B. In what proportion should the profit at the end of one year be distributed among A, B and C?", options: ["3:5:5", "6:10:5", "3:5:2", "Cannot be determined"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'partnership' },
  { id: 12099, question: "A and B entered into a partnership investing Rs. 16,000 and Rs. 12,000 respectively. After 3 months, A withdrew Rs. 5000 while B invested Rs. 5000 more. After 3 more months, C joins the business with a capital of Rs. 21,000. The share of B exceeds that of C, out of a total profit of Rs. 26,400 after one year, by:", options: ["Rs. 1200", "Rs. 2400", "Rs. 3600", "Rs. 4800"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'partnership' },
  { id: 12100, question: "A, B, C rent a pasture. A puts 10 oxen for 7 months, B puts 12 oxen for 5 months and C puts 15 oxen for 3 months for grazing. If the rent of the pasture is Rs. 175, how much must C pay as his share of rent?", options: ["Rs. 45", "Rs. 50", "Rs. 55", "Rs. 60"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'partnership' },

  // Algebra (10)
  { id: 12101, question: "If x + 5 = 12, what is the value of x?", options: ["7", "17", "-7", "5"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'algebra'},
  { id: 12102, question: "Simplify: 3a + 2b - a + 4b", options: ["2a + 6b", "4a + 6b", "2a + 2b", "4a + 2b"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'algebra'},
  { id: 12103, question: "Find the value of 2x + 3 when x = 4.", options: ["8", "11", "10", "14"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'algebra'},
  { id: 12104, question: "If 5y = 20, then y = ?", options: ["2", "4", "5", "100"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'algebra'},
  { id: 12105, question: "Find the value of x² when x = 9.", options: ["18", "81", "3", "27"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'algebra'},
  { id: 12106, question: "What is the sum of (a + b) and (a - b)?", options: ["2a", "2b", "a²+b²", "0"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'algebra'},
  { id: 12107, question: "If a = 2, b = 3, find the value of a² + b².", options: ["5", "13", "12", "25"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'algebra'},
  { id: 12108, question: "Solve for p: 3p - 2 = 7.", options: ["1", "2", "3", "9/3"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'algebra'},
  { id: 12109, question: "The product of (x+2) and (x+3) is:", options: ["x²+5x+6", "x²+6x+5", "x²+x+6", "x²+6"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'algebra'},
  { id: 12110, question: "If x/4 = 5, then x is:", options: ["1", "20", "9", "1.25"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'algebra'},
  
  // Geometry (10)
  { id: 12201, question: "The measure of an angle which is its own complement is:", options: ["30°", "45°", "60°", "90°"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'geometry' },
  { id: 12202, question: "How many diagonals does a regular hexagon have?", options: ["6", "9", "12", "15"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'geometry' },
  { id: 12203, question: "The angles of a triangle are in the ratio 2:3:4. The smallest angle is:", options: ["20°", "40°", "60°", "80°"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'geometry' },
  { id: 12204, question: "In a circle, the angle in a semicircle is a:", options: ["Right angle", "Acute angle", "Obtuse angle", "Straight angle"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'geometry' },
  { id: 12205, question: "The sum of all angles of a quadrilateral is:", options: ["180°", "270°", "360°", "540°"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'geometry' },
  { id: 12206, question: "Two lines that are parallel to the same line are:", options: ["Parallel to each other", "Perpendicular to each other", "Intersecting", "None of these"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'geometry' },
  { id: 12207, question: "The longest chord of a circle is its:", options: ["Radius", "Diameter", "Tangent", "Secant"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'geometry' },
  { id: 12208, question: "If the two legs of a right triangle are 3 cm and 4 cm, what is the length of the hypotenuse?", options: ["5 cm", "6 cm", "7 cm", "2.5 cm"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'geometry' },
  { id: 12209, question: "The number of vertices in a cuboid is:", options: ["4", "6", "8", "12"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'geometry' },
  { id: 12210, question: "An angle that is greater than 180° but less than 360° is called a:", options: ["Acute angle", "Obtuse angle", "Reflex angle", "Straight angle"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'geometry' },

  // Trigonometry (10)
  { id: 12301, question: "What is the value of sin 30°?", options: ["1/2", "√3/2", "1", "0"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'trigonometry' },
  { id: 12302, question: "If cos A = 4/5, then tan A is:", options: ["3/4", "4/3", "3/5", "5/3"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'trigonometry' },
  { id: 12303, question: "The value of tan 45° is:", options: ["0", "1/2", "1", "√3"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'trigonometry' },
  { id: 12304, question: "sin(90° - A) is equal to:", options: ["sin A", "cos A", "tan A", "-sin A"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'trigonometry' },
  { id: 12305, question: "The value of sin²θ + cos²θ is:", options: ["0", "1", "2", "-1"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'trigonometry' },
  { id: 12306, question: "A ladder 10 m long reaches a window 8 m above the ground. The distance of the foot of the ladder from the base of the wall is:", options: ["6 m", "18 m", "2 m", "12 m"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'trigonometry' },
  { id: 12307, question: "What is the value of 2 tan 30° / (1 + tan² 30°)?", options: ["sin 60°", "cos 60°", "tan 60°", "sin 30°"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'trigonometry' },
  { id: 12308, question: "If sec θ = 13/12, then cos θ is:", options: ["12/13", "5/12", "5/13", "13/5"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'trigonometry' },
  { id: 12309, question: "The value of cosec 30° is:", options: ["1/2", "2", "√2", "1/√2"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'trigonometry' },
  { id: 12310, question: "If tan A = cot B, then A + B = ?", options: ["0°", "45°", "90°", "180°"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'trigonometry' },

  // Mensuration (10)
  { id: 12401, question: "The perimeter of a square with side 5 cm is:", options: ["10 cm", "15 cm", "20 cm", "25 cm"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'mensuration' },
  { id: 12402, question: "The area of a rectangle with length 8 cm and breadth 6 cm is:", options: ["14 cm²", "28 cm²", "48 cm²", "36 cm²"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'mensuration' },
  { id: 12403, question: "The circumference of a circle with diameter 14 cm is:", options: ["22 cm", "44 cm", "88 cm", "616 cm"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'mensuration' },
  { id: 12404, question: "The volume of a cuboid with dimensions 2cm x 3cm x 4cm is:", options: ["9 cm³", "12 cm³", "24 cm³", "36 cm³"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'mensuration' },
  { id: 12405, question: "The area of a circle with radius 7 cm is:", options: ["44 cm²", "154 cm²", "77 cm²", "14 cm²"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'mensuration' },
  { id: 12406, question: "The total surface area of a cube with side 4 cm is:", options: ["64 cm²", "96 cm²", "16 cm²", "80 cm²"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'mensuration' },
  { id: 12407, question: "The perimeter of an equilateral triangle with side 6 cm is:", options: ["12 cm", "18 cm", "24 cm", "36 cm"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'mensuration' },
  { id: 12408, question: "The volume of a cylinder with radius 7 cm and height 5 cm is:", options: ["770 cm³", "550 cm³", "385 cm³", "154 cm³"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'mensuration' },
  { id: 12409, question: "The area of a parallelogram with base 10 cm and height 5 cm is:", options: ["50 cm²", "15 cm²", "30 cm²", "100 cm²"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'mensuration' },
  { id: 12410, question: "The surface area of a sphere with radius 7 cm is:", options: ["154 cm²", "308 cm²", "462 cm²", "616 cm²"], correctAnswerIndex: 3, subject: 'Maths', exam: 'SSC MTS', chapter: 'mensuration' },

  // Statistics, Probability, DI, Coordinate Geometry (10)
  { id: 12501, question: "Find the mean of 2, 4, 6, 8, 10.", options: ["6", "5", "7", "4"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'statistics' },
  { id: 12502, question: "A bag contains 3 red and 2 blue balls. What is the probability of drawing a red ball?", options: ["2/5", "3/5", "1/2", "1"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'probability' },
  { id: 12503, question: "Find the median of 10, 20, 15, 25, 5.", options: ["10", "20", "15", "5"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'statistics' },
  { id: 12504, question: "The point (2, 3) lies in which quadrant?", options: ["I", "II", "III", "IV"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'coordinate-geometry' },
  { id: 12505, question: "A die is thrown. What is the probability of getting an even number?", options: ["1/2", "1/3", "1/6", "1"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'probability' },
  { id: 12506, question: "Find the mode of 5, 6, 7, 7, 8, 8, 8, 9.", options: ["7", "8", "9", "5"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'statistics' },
  { id: 12507, question: "What is the distance of point (4, 3) from the y-axis?", options: ["3", "4", "5", "7"], correctAnswerIndex: 1, subject: 'Maths', exam: 'SSC MTS', chapter: 'coordinate-geometry' },
  { id: 12508, question: "If a coin is tossed twice, what is the probability of getting at least one head?", options: ["1/4", "1/2", "3/4", "1"], correctAnswerIndex: 2, subject: 'Maths', exam: 'SSC MTS', chapter: 'probability' },
  { id: 12509, question: "A bar chart shows runs scored by a team: 150, 200, 180, 220. What is the average score?", options: ["187.5", "190", "185", "180"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'di' },
  { id: 12510, question: "The point where the x-axis and y-axis intersect is called the:", options: ["Origin", "Quadrant", "Coordinate", "Abscissa"], correctAnswerIndex: 0, subject: 'Maths', exam: 'SSC MTS', chapter: 'coordinate-geometry' },

  // --- General Studies (Easy/Moderate) - 25 questions ---
  { id: 22001, question: "Who was the first Prime Minister of India?", options: ["Mahatma Gandhi", "Sardar Patel", "Jawaharlal Nehru", "Dr. Rajendra Prasad"], correctAnswerIndex: 2, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22002, question: "Which planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Saturn"], correctAnswerIndex: 1, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22003, question: "What is the capital of Japan?", options: ["Beijing", "Seoul", "Tokyo", "Bangkok"], correctAnswerIndex: 2, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22004, question: "The 'Ganges' river originates from which glacier?", options: ["Yamunotri", "Siachen", "Gangotri", "Pindari"], correctAnswerIndex: 2, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22005, question: "Who wrote 'Ramcharitmanas'?", options: ["Tulsidas", "Valmiki", "Kalidas", "Ved Vyas"], correctAnswerIndex: 0, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22006, question: "Which is the largest state in India by area?", options: ["Maharashtra", "Madhya Pradesh", "Uttar Pradesh", "Rajasthan"], correctAnswerIndex: 3, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22007, question: "Sound cannot travel through:", options: ["Air", "Water", "Steel", "Vacuum"], correctAnswerIndex: 3, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22008, question: "Who invented the telephone?", options: ["Thomas Edison", "Alexander Graham Bell", "Guglielmo Marconi", "James Watt"], correctAnswerIndex: 1, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22009, question: "How many states are there in India?", options: ["28", "29", "30", "27"], correctAnswerIndex: 0, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22010, question: "Which festival is known as the festival of lights?", options: ["Holi", "Diwali", "Eid", "Christmas"], correctAnswerIndex: 1, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22011, question: "What is the full form of CPU?", options: ["Central Processing Unit", "Central Program Unit", "Computer Processing Unit", "Central Power Unit"], correctAnswerIndex: 0, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22012, question: "Who was the first man to walk on the moon?", options: ["Yuri Gagarin", "Neil Armstrong", "Rakesh Sharma", "Buzz Aldrin"], correctAnswerIndex: 1, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22013, question: "Which is the hardest substance available on earth?", options: ["Gold", "Iron", "Diamond", "Platinum"], correctAnswerIndex: 2, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22014, question: "The 'Dandi March' was started by Mahatma Gandhi in which year?", options: ["1920", "1930", "1942", "1928"], correctAnswerIndex: 1, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22015, question: "What is the national animal of India?", options: ["Lion", "Tiger", "Elephant", "Leopard"], correctAnswerIndex: 1, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22016, question: "Who built the Taj Mahal?", options: ["Akbar", "Jahangir", "Shah Jahan", "Aurangzeb"], correctAnswerIndex: 2, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22017, question: "Which Indian city is known as the 'Pink City'?", options: ["Jaipur", "Udaipur", "Jodhpur", "Delhi"], correctAnswerIndex: 0, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22018, question: "Which is the main gas that causes the greenhouse effect?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], correctAnswerIndex: 2, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22019, question: "Who is known as the 'Father of the Nation' in India?", options: ["Sardar Patel", "Jawaharlal Nehru", "Mahatma Gandhi", "Dr. B. R. Ambedkar"], correctAnswerIndex: 2, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22020, question: "What is the currency of the USA?", options: ["Euro", "Yen", "Pound", "Dollar"], correctAnswerIndex: 3, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22021, question: "Which of the following is an input device for a computer?", options: ["Monitor", "Printer", "Keyboard", "Speaker"], correctAnswerIndex: 2, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22022, question: "The headquarters of the United Nations (UN) is located in:", options: ["Geneva", "New York City", "Paris", "Washington D.C."], correctAnswerIndex: 1, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22023, question: "Which is the largest ocean in the world?", options: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"], correctAnswerIndex: 3, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22024, question: "The human skeleton is composed of how many bones?", options: ["206", "208", "201", "300"], correctAnswerIndex: 0, subject: 'General Studies', exam: 'SSC MTS' },
  { id: 22025, question: "What is the boiling point of water?", options: ["0°C", "50°C", "100°C", "150°C"], correctAnswerIndex: 2, subject: 'General Studies', exam: 'SSC MTS' },

  // --- Reasoning (Easy/Moderate) - 25 questions ---
  { id: 32001, question: "Which number will complete the series? 2, 4, 6, 8, ?", options: ["10", "12", "9", "11"], correctAnswerIndex: 0, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32002, question: "If 'Book' is related to 'Read', then 'Pen' is related to:", options: ["Write", "Ink", "Paper", "Blue"], correctAnswerIndex: 0, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32003, question: "Find the odd one out: Apple, Banana, Carrot, Mango.", options: ["Apple", "Banana", "Carrot", "Mango"], correctAnswerIndex: 2, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32004, question: "Complete the series: A, C, E, G, ?", options: ["H", "I", "J", "K"], correctAnswerIndex: 1, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32005, question: "If 'HOT' is coded as 'SGL', then what is the code for 'COLD'?", options: ["XLOW", "XMPW", "XLOW", "XLOW"], correctAnswerIndex: 0, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32006, question: "A man walks 5 km East, then 5 km South. In which direction is he from his starting point?", options: ["North-East", "South-West", "South-East", "North-West"], correctAnswerIndex: 2, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32007, question: "Which of the following is a leap year?", options: ["1900", "2002", "2004", "2100"], correctAnswerIndex: 2, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32008, question: "Doctor : Patient :: Lawyer : ?", options: ["Client", "Customer", "Accused", "Magistrate"], correctAnswerIndex: 0, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32009, question: "Arrange the words in a logical order: 1. Key 2. Door 3. Lock 4. Room 5. Switch on", options: ["5, 1, 2, 3, 4", "1, 3, 2, 4, 5", "4, 2, 1, 3, 5", "1, 2, 3, 5, 4"], correctAnswerIndex: 1, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32010, question: "Find the missing number: 8, 27, 64, ?, 216", options: ["100", "125", "150", "180"], correctAnswerIndex: 1, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32011, question: "Ravi's mother is the only daughter of Monika's father. How is Monika's husband related to Ravi?", options: ["Uncle", "Father", "Brother", "Grandfather"], correctAnswerIndex: 1, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32012, question: "Find the odd one out: January, May, July, November", options: ["January", "May", "July", "November"], correctAnswerIndex: 3, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32013, question: "Complete the pattern: 1, 4, 9, 16, 25, ?", options: ["30", "36", "49", "64"], correctAnswerIndex: 1, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32014, question: "If '+' means 'x' and '-' means '+', what is the value of 5 + 3 - 2?", options: ["13", "17", "6", "5"], correctAnswerIndex: 1, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32015, question: "In a certain code, '253' means 'books are old'; '546' means 'man is old'; '378' means 'buy good books'. What stands for 'are' in that code?", options: ["2", "3", "5", "6"], correctAnswerIndex: 0, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32016, question: "Which of the following diagrams best represents the relationship between 'Table', 'Chair', 'Furniture'?", options: ["Diagram A", "Diagram B", "Diagram C", "Diagram D"], correctAnswerIndex: 0, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32017, question: "If Z=52 and ACT=48, then BAT will be equal to:", options: ["39", "41", "44", "46"], correctAnswerIndex: 3, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32018, question: "A is taller than B, C is taller than A. D is taller than E but shorter than B. Who is the tallest?", options: ["A", "B", "C", "D"], correctAnswerIndex: 2, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32019, question: "Find the next pair of letters in the series: AZ, CX, FU, ?", options: ["IR", "IV", "JQ", "KP"], correctAnswerIndex: 2, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32020, question: "How many meaningful English words can be made with the letters 'A, E, R' using each letter only once in each word?", options: ["One", "Two", "Three", "Four"], correctAnswerIndex: 1, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32021, question: "If the 3rd day of a month is Monday, which of the following will be the 25th day of the month?", options: ["Monday", "Tuesday", "Wednesday", "Sunday"], correctAnswerIndex: 2, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32022, question: "Eye : See :: Ear : ?", options: ["Hear", "Smell", "Taste", "Touch"], correctAnswerIndex: 0, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32023, question: "Find the number of triangles in the given figure.", options: ["5", "6", "7", "8"], correctAnswerIndex: 3, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32024, question: "If day-after-tomorrow is Saturday, what day was three days before yesterday?", options: ["Sunday", "Monday", "Tuesday", "Wednesday"], correctAnswerIndex: 0, subject: 'Reasoning', exam: 'SSC MTS' },
  { id: 32025, question: "Select the missing number from the given responses. 9, 12, 15, ?, 21", options: ["16", "17", "18", "19"], correctAnswerIndex: 2, subject: 'Reasoning', exam: 'SSC MTS' },

  // --- English (Easy/Moderate) - 25 questions ---
  { id: 42001, question: "What is the opposite of 'Happy'?", options: ["Joyful", "Glad", "Sad", "Cheerful"], correctAnswerIndex: 2, subject: 'English', exam: 'SSC MTS' },
  { id: 42002, question: "What is the plural of 'child'?", options: ["Childs", "Children", "Childes", "Childer"], correctAnswerIndex: 1, subject: 'English', exam: 'SSC MTS' },
  { id: 42003, question: "Choose the correct verb: The dogs ___ barking.", options: ["is", "am", "are", "was"], correctAnswerIndex: 2, subject: 'English', exam: 'SSC MTS' },
  { id: 42004, question: "Select the correctly spelt word.", options: ["Grammer", "Grammar", "Gramer", "Gramar"], correctAnswerIndex: 1, subject: 'English', exam: 'SSC MTS' },
  { id: 42005, question: "Choose the synonym for 'Start'.", options: ["Stop", "End", "Begin", "Finish"], correctAnswerIndex: 2, subject: 'English', exam: 'SSC MTS' },
  { id: 42006, question: "Fill in the blank: The book is ____ the table.", options: ["on", "in", "at", "with"], correctAnswerIndex: 0, subject: 'English', exam: 'SSC MTS' },
  { id: 42007, question: "What is the past tense of 'go'?", options: ["Goed", "Gone", "Went", "Goes"], correctAnswerIndex: 2, subject: 'English', exam: 'SSC MTS' },
  { id: 42008, question: "Identify the noun in the sentence: 'The cat is sleeping.'", options: ["The", "Cat", "Is", "Sleeping"], correctAnswerIndex: 1, subject: 'English', exam: 'SSC MTS' },
  { id: 42009, question: "Select the antonym for 'Big'.", options: ["Large", "Huge", "Small", "Giant"], correctAnswerIndex: 2, subject: 'English', exam: 'SSC MTS' },
  { id: 42010, question: "Choose the correct article: I saw ____ elephant.", options: ["a", "an", "the", "no article"], correctAnswerIndex: 1, subject: 'English', exam: 'SSC MTS' },
  { id: 42011, question: "Which word means 'a place where birds are kept'?", options: ["Aquarium", "Aviary", "Apiary", "Zoo"], correctAnswerIndex: 1, subject: 'English', exam: 'SSC MTS' },
  { id: 42012, question: "Select the part of speech of the underlined word: She sings 'beautifully'.", options: ["Adjective", "Verb", "Adverb", "Noun"], correctAnswerIndex: 2, subject: 'English', exam: 'SSC MTS' },
  { id: 42013, question: "What is the plural of 'man'?", options: ["Mans", "Manes", "Mens", "Men"], correctAnswerIndex: 3, subject: 'English', exam: 'SSC MTS' },
  { id: 42014, question: "Find the error: 'He don't like coffee.'", options: ["He", "don't like", "coffee", "No error"], correctAnswerIndex: 1, subject: 'English', exam: 'SSC MTS' },
  { id: 42015, question: "Choose the synonym of 'Quick'.", options: ["Slow", "Lazy", "Fast", "Dull"], correctAnswerIndex: 2, subject: 'English', exam: 'SSC MTS' },
  { id: 42016, question: "Fill in the blank: I am fond ____ music.", options: ["of", "in", "with", "to"], correctAnswerIndex: 0, subject: 'English', exam: 'SSC MTS' },
  { id: 42017, question: "Select the correctly spelt word.", options: ["Toomorrow", "Tommorrow", "Tomorrow", "Tommorow"], correctAnswerIndex: 2, subject: 'English', exam: 'SSC MTS' },
  { id: 42018, question: "What is the opposite of 'Hot'?", options: ["Warm", "Cold", "Boiling", "Sunny"], correctAnswerIndex: 1, subject: 'English', exam: 'SSC MTS' },
  { id: 42019, question: "Choose the correct sentence.", options: ["She is more taller than him.", "She is taller than him.", "She is tallest than him.", "She is more tall than him."], correctAnswerIndex: 1, subject: 'English', exam: 'SSC MTS' },
  { id: 42020, question: "A person who writes books is called an:", options: ["Author", "Editor", "Publisher", "Reader"], correctAnswerIndex: 0, subject: 'English', exam: 'SSC MTS' },
  { id: 42021, question: "What is the feminine gender of 'horse'?", options: ["Doe", "Mare", "Vixen", "Goose"], correctAnswerIndex: 1, subject: 'English', exam: 'SSC MTS' },
  { id: 42022, question: "Fill in the blank: He is afraid ____ dogs.", options: ["from", "with", "of", "to"], correctAnswerIndex: 2, subject: 'English', exam: 'SSC MTS' },
  { id: 42023, question: "Select the synonym for 'Beautiful'.", options: ["Ugly", "Pretty", "Plain", "Horrible"], correctAnswerIndex: 1, subject: 'English', exam: 'SSC MTS' },
  { id: 42024, question: "Find the error: 'My brother have a new car.'", options: ["My brother", "have a new car", "No error"], correctAnswerIndex: 1, subject: 'English', exam: 'SSC MTS' },
  { id: 42025, question: "What do you call a person who cannot read or write?", options: ["Illiterate", "Ignorant", "Uneducated", "Scholar"], correctAnswerIndex: 0, subject: 'English', exam: 'SSC MTS' },
];
